//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 04:52:12 PM CEST 
//


package com.terradue.ogf.schema.jsdl.impl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FileSystemTypeEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FileSystemTypeEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="swap"/>
 *     &lt;enumeration value="temporary"/>
 *     &lt;enumeration value="spool"/>
 *     &lt;enumeration value="normal"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FileSystemTypeEnumeration")
@XmlEnum
public enum FileSystemTypeEnumeration {

    @XmlEnumValue("swap")
    SWAP("swap"),
    @XmlEnumValue("temporary")
    TEMPORARY("temporary"),
    @XmlEnumValue("spool")
    SPOOL("spool"),
    @XmlEnumValue("normal")
    NORMAL("normal");
    private final String value;

    FileSystemTypeEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FileSystemTypeEnumeration fromValue(String v) {
        for (FileSystemTypeEnumeration c: FileSystemTypeEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
