//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 04:52:12 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.ggf.org/jsdl/2005/11/jsdl", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.terradue.ogf.schema.jsdl.impl;
