//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 04:52:12 PM CEST 
//


package com.terradue.ogf.schema.jsdl.impl;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.w3c.dom.Element;


/**
 * <p>Java class for Resources_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Resources_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl}CandidateHosts" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl}FileSystem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl}ExclusiveExecution" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl}OperatingSystem" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl}CPUArchitecture" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl}IndividualCPUSpeed" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl}IndividualCPUTime" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl}IndividualCPUCount" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl}IndividualNetworkBandwidth" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl}IndividualPhysicalMemory" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl}IndividualVirtualMemory" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl}IndividualDiskSpace" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl}TotalCPUTime" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl}TotalCPUCount" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl}TotalPhysicalMemory" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl}TotalVirtualMemory" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl}TotalDiskSpace" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl}TotalResourceCount" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Resources_Type", propOrder = {
    "candidateHosts",
    "fileSystem",
    "exclusiveExecution",
    "operatingSystem",
    "cpuArchitecture",
    "individualCPUSpeed",
    "individualCPUTime",
    "individualCPUCount",
    "individualNetworkBandwidth",
    "individualPhysicalMemory",
    "individualVirtualMemory",
    "individualDiskSpace",
    "totalCPUTime",
    "totalCPUCount",
    "totalPhysicalMemory",
    "totalVirtualMemory",
    "totalDiskSpace",
    "totalResourceCount",
    "any"
})
public class ResourcesType {

    @XmlElement(name = "CandidateHosts")
    protected CandidateHostsType candidateHosts;
    @XmlElement(name = "FileSystem")
    protected List<FileSystemType> fileSystem;
    @XmlElement(name = "ExclusiveExecution")
    protected Boolean exclusiveExecution;
    @XmlElement(name = "OperatingSystem")
    protected OperatingSystemType operatingSystem;
    @XmlElement(name = "CPUArchitecture")
    protected CPUArchitectureType cpuArchitecture;
    @XmlElement(name = "IndividualCPUSpeed")
    protected RangeValueType individualCPUSpeed;
    @XmlElement(name = "IndividualCPUTime")
    protected RangeValueType individualCPUTime;
    @XmlElement(name = "IndividualCPUCount")
    protected RangeValueType individualCPUCount;
    @XmlElement(name = "IndividualNetworkBandwidth")
    protected RangeValueType individualNetworkBandwidth;
    @XmlElement(name = "IndividualPhysicalMemory")
    protected RangeValueType individualPhysicalMemory;
    @XmlElement(name = "IndividualVirtualMemory")
    protected RangeValueType individualVirtualMemory;
    @XmlElement(name = "IndividualDiskSpace")
    protected RangeValueType individualDiskSpace;
    @XmlElement(name = "TotalCPUTime")
    protected RangeValueType totalCPUTime;
    @XmlElement(name = "TotalCPUCount")
    protected RangeValueType totalCPUCount;
    @XmlElement(name = "TotalPhysicalMemory")
    protected RangeValueType totalPhysicalMemory;
    @XmlElement(name = "TotalVirtualMemory")
    protected RangeValueType totalVirtualMemory;
    @XmlElement(name = "TotalDiskSpace")
    protected RangeValueType totalDiskSpace;
    @XmlElement(name = "TotalResourceCount")
    protected RangeValueType totalResourceCount;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the candidateHosts property.
     * 
     * @return
     *     possible object is
     *     {@link CandidateHostsType }
     *     
     */
    public CandidateHostsType getCandidateHosts() {
        return candidateHosts;
    }

    /**
     * Sets the value of the candidateHosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link CandidateHostsType }
     *     
     */
    public void setCandidateHosts(CandidateHostsType value) {
        this.candidateHosts = value;
    }

    /**
     * Gets the value of the fileSystem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fileSystem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFileSystem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FileSystemType }
     * 
     * 
     */
    public List<FileSystemType> getFileSystem() {
        if (fileSystem == null) {
            fileSystem = new ArrayList<FileSystemType>();
        }
        return this.fileSystem;
    }

    /**
     * Gets the value of the exclusiveExecution property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExclusiveExecution() {
        return exclusiveExecution;
    }

    /**
     * Sets the value of the exclusiveExecution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExclusiveExecution(Boolean value) {
        this.exclusiveExecution = value;
    }

    /**
     * Gets the value of the operatingSystem property.
     * 
     * @return
     *     possible object is
     *     {@link OperatingSystemType }
     *     
     */
    public OperatingSystemType getOperatingSystem() {
        return operatingSystem;
    }

    /**
     * Sets the value of the operatingSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatingSystemType }
     *     
     */
    public void setOperatingSystem(OperatingSystemType value) {
        this.operatingSystem = value;
    }

    /**
     * Gets the value of the cpuArchitecture property.
     * 
     * @return
     *     possible object is
     *     {@link CPUArchitectureType }
     *     
     */
    public CPUArchitectureType getCPUArchitecture() {
        return cpuArchitecture;
    }

    /**
     * Sets the value of the cpuArchitecture property.
     * 
     * @param value
     *     allowed object is
     *     {@link CPUArchitectureType }
     *     
     */
    public void setCPUArchitecture(CPUArchitectureType value) {
        this.cpuArchitecture = value;
    }

    /**
     * Gets the value of the individualCPUSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link RangeValueType }
     *     
     */
    public RangeValueType getIndividualCPUSpeed() {
        return individualCPUSpeed;
    }

    /**
     * Sets the value of the individualCPUSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link RangeValueType }
     *     
     */
    public void setIndividualCPUSpeed(RangeValueType value) {
        this.individualCPUSpeed = value;
    }

    /**
     * Gets the value of the individualCPUTime property.
     * 
     * @return
     *     possible object is
     *     {@link RangeValueType }
     *     
     */
    public RangeValueType getIndividualCPUTime() {
        return individualCPUTime;
    }

    /**
     * Sets the value of the individualCPUTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link RangeValueType }
     *     
     */
    public void setIndividualCPUTime(RangeValueType value) {
        this.individualCPUTime = value;
    }

    /**
     * Gets the value of the individualCPUCount property.
     * 
     * @return
     *     possible object is
     *     {@link RangeValueType }
     *     
     */
    public RangeValueType getIndividualCPUCount() {
        return individualCPUCount;
    }

    /**
     * Sets the value of the individualCPUCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link RangeValueType }
     *     
     */
    public void setIndividualCPUCount(RangeValueType value) {
        this.individualCPUCount = value;
    }

    /**
     * Gets the value of the individualNetworkBandwidth property.
     * 
     * @return
     *     possible object is
     *     {@link RangeValueType }
     *     
     */
    public RangeValueType getIndividualNetworkBandwidth() {
        return individualNetworkBandwidth;
    }

    /**
     * Sets the value of the individualNetworkBandwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link RangeValueType }
     *     
     */
    public void setIndividualNetworkBandwidth(RangeValueType value) {
        this.individualNetworkBandwidth = value;
    }

    /**
     * Gets the value of the individualPhysicalMemory property.
     * 
     * @return
     *     possible object is
     *     {@link RangeValueType }
     *     
     */
    public RangeValueType getIndividualPhysicalMemory() {
        return individualPhysicalMemory;
    }

    /**
     * Sets the value of the individualPhysicalMemory property.
     * 
     * @param value
     *     allowed object is
     *     {@link RangeValueType }
     *     
     */
    public void setIndividualPhysicalMemory(RangeValueType value) {
        this.individualPhysicalMemory = value;
    }

    /**
     * Gets the value of the individualVirtualMemory property.
     * 
     * @return
     *     possible object is
     *     {@link RangeValueType }
     *     
     */
    public RangeValueType getIndividualVirtualMemory() {
        return individualVirtualMemory;
    }

    /**
     * Sets the value of the individualVirtualMemory property.
     * 
     * @param value
     *     allowed object is
     *     {@link RangeValueType }
     *     
     */
    public void setIndividualVirtualMemory(RangeValueType value) {
        this.individualVirtualMemory = value;
    }

    /**
     * Gets the value of the individualDiskSpace property.
     * 
     * @return
     *     possible object is
     *     {@link RangeValueType }
     *     
     */
    public RangeValueType getIndividualDiskSpace() {
        return individualDiskSpace;
    }

    /**
     * Sets the value of the individualDiskSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link RangeValueType }
     *     
     */
    public void setIndividualDiskSpace(RangeValueType value) {
        this.individualDiskSpace = value;
    }

    /**
     * Gets the value of the totalCPUTime property.
     * 
     * @return
     *     possible object is
     *     {@link RangeValueType }
     *     
     */
    public RangeValueType getTotalCPUTime() {
        return totalCPUTime;
    }

    /**
     * Sets the value of the totalCPUTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link RangeValueType }
     *     
     */
    public void setTotalCPUTime(RangeValueType value) {
        this.totalCPUTime = value;
    }

    /**
     * Gets the value of the totalCPUCount property.
     * 
     * @return
     *     possible object is
     *     {@link RangeValueType }
     *     
     */
    public RangeValueType getTotalCPUCount() {
        return totalCPUCount;
    }

    /**
     * Sets the value of the totalCPUCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link RangeValueType }
     *     
     */
    public void setTotalCPUCount(RangeValueType value) {
        this.totalCPUCount = value;
    }

    /**
     * Gets the value of the totalPhysicalMemory property.
     * 
     * @return
     *     possible object is
     *     {@link RangeValueType }
     *     
     */
    public RangeValueType getTotalPhysicalMemory() {
        return totalPhysicalMemory;
    }

    /**
     * Sets the value of the totalPhysicalMemory property.
     * 
     * @param value
     *     allowed object is
     *     {@link RangeValueType }
     *     
     */
    public void setTotalPhysicalMemory(RangeValueType value) {
        this.totalPhysicalMemory = value;
    }

    /**
     * Gets the value of the totalVirtualMemory property.
     * 
     * @return
     *     possible object is
     *     {@link RangeValueType }
     *     
     */
    public RangeValueType getTotalVirtualMemory() {
        return totalVirtualMemory;
    }

    /**
     * Sets the value of the totalVirtualMemory property.
     * 
     * @param value
     *     allowed object is
     *     {@link RangeValueType }
     *     
     */
    public void setTotalVirtualMemory(RangeValueType value) {
        this.totalVirtualMemory = value;
    }

    /**
     * Gets the value of the totalDiskSpace property.
     * 
     * @return
     *     possible object is
     *     {@link RangeValueType }
     *     
     */
    public RangeValueType getTotalDiskSpace() {
        return totalDiskSpace;
    }

    /**
     * Sets the value of the totalDiskSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link RangeValueType }
     *     
     */
    public void setTotalDiskSpace(RangeValueType value) {
        this.totalDiskSpace = value;
    }

    /**
     * Gets the value of the totalResourceCount property.
     * 
     * @return
     *     possible object is
     *     {@link RangeValueType }
     *     
     */
    public RangeValueType getTotalResourceCount() {
        return totalResourceCount;
    }

    /**
     * Sets the value of the totalResourceCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link RangeValueType }
     *     
     */
    public void setTotalResourceCount(RangeValueType value) {
        this.totalResourceCount = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
