//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 04:52:12 PM CEST 
//


package com.terradue.ogf.schema.jsdl.impl;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;
import org.w3c.dom.Element;


/**
 * <p>Java class for SPMDApplication_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SPMDApplication_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl-posix}Executable" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl-posix}Argument" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl-posix}Input" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl-posix}Output" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl-posix}Error" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl-posix}WorkingDirectory" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl-posix}Environment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ggf.org/jsdl/2005/11/jsdl-posix}UserName" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ogf.org/jsdl/2007/02/jsdl-spmd}NumberOfProcesses" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ogf.org/jsdl/2007/02/jsdl-spmd}ProcessesPerHost" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ogf.org/jsdl/2007/02/jsdl-spmd}ThreadsPerProcess" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.ogf.org/jsdl/2007/02/jsdl-spmd}SPMDVariation"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SPMDApplication_Type", namespace = "http://schemas.ogf.org/jsdl/2007/02/jsdl-spmd", propOrder = {
    "executable",
    "argument",
    "input",
    "output",
    "error",
    "workingDirectory",
    "environment",
    "userName",
    "numberOfProcesses",
    "processesPerHost",
    "threadsPerProcess",
    "spmdVariation",
    "any"
})
public class SPMDApplicationType {

    @XmlElement(name = "Executable", namespace = "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix")
    protected FileNameType executable;
    @XmlElement(name = "Argument", namespace = "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix")
    protected List<ArgumentType> argument;
    @XmlElement(name = "Input", namespace = "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix")
    protected FileNameType input;
    @XmlElement(name = "Output", namespace = "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix")
    protected FileNameType output;
    @XmlElement(name = "Error", namespace = "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix")
    protected FileNameType error;
    @XmlElement(name = "WorkingDirectory", namespace = "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix")
    protected DirectoryNameType workingDirectory;
    @XmlElement(name = "Environment", namespace = "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix")
    protected List<EnvironmentType> environment;
    @XmlElement(name = "UserName", namespace = "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix")
    protected UserNameType userName;
    @XmlElement(name = "NumberOfProcesses", nillable = true)
    protected NumberOfProcessesType numberOfProcesses;
    @XmlElement(name = "ProcessesPerHost")
    protected ProcessesPerHostType processesPerHost;
    @XmlElement(name = "ThreadsPerProcess", nillable = true)
    protected ThreadsPerProcessType threadsPerProcess;
    @XmlElement(name = "SPMDVariation", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String spmdVariation;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the executable property.
     * 
     * @return
     *     possible object is
     *     {@link FileNameType }
     *     
     */
    public FileNameType getExecutable() {
        return executable;
    }

    /**
     * Sets the value of the executable property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileNameType }
     *     
     */
    public void setExecutable(FileNameType value) {
        this.executable = value;
    }

    /**
     * Gets the value of the argument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the argument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArgument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArgumentType }
     * 
     * 
     */
    public List<ArgumentType> getArgument() {
        if (argument == null) {
            argument = new ArrayList<ArgumentType>();
        }
        return this.argument;
    }

    /**
     * Gets the value of the input property.
     * 
     * @return
     *     possible object is
     *     {@link FileNameType }
     *     
     */
    public FileNameType getInput() {
        return input;
    }

    /**
     * Sets the value of the input property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileNameType }
     *     
     */
    public void setInput(FileNameType value) {
        this.input = value;
    }

    /**
     * Gets the value of the output property.
     * 
     * @return
     *     possible object is
     *     {@link FileNameType }
     *     
     */
    public FileNameType getOutput() {
        return output;
    }

    /**
     * Sets the value of the output property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileNameType }
     *     
     */
    public void setOutput(FileNameType value) {
        this.output = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link FileNameType }
     *     
     */
    public FileNameType getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileNameType }
     *     
     */
    public void setError(FileNameType value) {
        this.error = value;
    }

    /**
     * Gets the value of the workingDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryNameType }
     *     
     */
    public DirectoryNameType getWorkingDirectory() {
        return workingDirectory;
    }

    /**
     * Sets the value of the workingDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryNameType }
     *     
     */
    public void setWorkingDirectory(DirectoryNameType value) {
        this.workingDirectory = value;
    }

    /**
     * Gets the value of the environment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the environment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnvironment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnvironmentType }
     * 
     * 
     */
    public List<EnvironmentType> getEnvironment() {
        if (environment == null) {
            environment = new ArrayList<EnvironmentType>();
        }
        return this.environment;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link UserNameType }
     *     
     */
    public UserNameType getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserNameType }
     *     
     */
    public void setUserName(UserNameType value) {
        this.userName = value;
    }

    /**
     * Gets the value of the numberOfProcesses property.
     * 
     * @return
     *     possible object is
     *     {@link NumberOfProcessesType }
     *     
     */
    public NumberOfProcessesType getNumberOfProcesses() {
        return numberOfProcesses;
    }

    /**
     * Sets the value of the numberOfProcesses property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberOfProcessesType }
     *     
     */
    public void setNumberOfProcesses(NumberOfProcessesType value) {
        this.numberOfProcesses = value;
    }

    /**
     * Gets the value of the processesPerHost property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessesPerHostType }
     *     
     */
    public ProcessesPerHostType getProcessesPerHost() {
        return processesPerHost;
    }

    /**
     * Sets the value of the processesPerHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessesPerHostType }
     *     
     */
    public void setProcessesPerHost(ProcessesPerHostType value) {
        this.processesPerHost = value;
    }

    /**
     * Gets the value of the threadsPerProcess property.
     * 
     * @return
     *     possible object is
     *     {@link ThreadsPerProcessType }
     *     
     */
    public ThreadsPerProcessType getThreadsPerProcess() {
        return threadsPerProcess;
    }

    /**
     * Sets the value of the threadsPerProcess property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThreadsPerProcessType }
     *     
     */
    public void setThreadsPerProcess(ThreadsPerProcessType value) {
        this.threadsPerProcess = value;
    }

    /**
     * Gets the value of the spmdVariation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPMDVariation() {
        return spmdVariation;
    }

    /**
     * Sets the value of the spmdVariation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPMDVariation(String value) {
        this.spmdVariation = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
