//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 05:26:33 PM CEST 
//


package com.terradue.ogf.schema.glue.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.terradue.ogf.schema.glue.impl.ApplicationEnvironmentT.Associations;


/**
 * <p>Java class for ApplicationEnvironment_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicationEnvironment_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}Entity">
 *       &lt;sequence>
 *         &lt;element name="LocalID" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}LocalID_t"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Repository" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="State" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}AppEnvState_t" minOccurs="0"/>
 *         &lt;element name="RemovalDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="License" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}License_t" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BestBenchmark" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}BenchmarkType_t" minOccurs="0"/>
 *         &lt;element name="ParallelSupport" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ParallelSupport_t" minOccurs="0"/>
 *         &lt;element name="MaxSlots" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="MaxJobs" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="MaxUserSeats" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="FreeSlots" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="FreeJobs" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="FreeUserSeats" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="Extensions" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}Extensions_t" minOccurs="0"/>
 *         &lt;element name="ApplicationHandle" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ApplicationHandle_t" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Associations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ExecutionEnvironmentLocalID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationEnvironment_t", propOrder = {
    "localID",
    "name",
    "version",
    "repository",
    "state",
    "removalDate",
    "license",
    "description",
    "bestBenchmark",
    "parallelSupport",
    "maxSlots",
    "maxJobs",
    "maxUserSeats",
    "freeSlots",
    "freeJobs",
    "freeUserSeats",
    "extensions",
    "applicationHandle",
    "associations"
})
public class ApplicationEnvironmentT
    extends Entity
{

    @XmlElement(name = "LocalID", required = true)
    protected String localID;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Version")
    protected String version;
    @XmlElement(name = "Repository")
    protected String repository;
    @XmlElement(name = "State")
    protected String state;
    @XmlElement(name = "RemovalDate")
    protected XMLGregorianCalendar removalDate;
    @XmlElement(name = "License")
    protected LicenseT license;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "BestBenchmark")
    protected String bestBenchmark;
    @XmlElement(name = "ParallelSupport")
    protected String parallelSupport;
    @XmlElement(name = "MaxSlots")
    protected Long maxSlots;
    @XmlElement(name = "MaxJobs")
    protected Long maxJobs;
    @XmlElement(name = "MaxUserSeats")
    protected Long maxUserSeats;
    @XmlElement(name = "FreeSlots")
    protected Long freeSlots;
    @XmlElement(name = "FreeJobs")
    protected Long freeJobs;
    @XmlElement(name = "FreeUserSeats")
    protected Long freeUserSeats;
    @XmlElement(name = "Extensions")
    protected ExtensionsT extensions;
    @XmlElement(name = "ApplicationHandle", required = true)
    protected List<ApplicationHandleT> applicationHandle;
    @XmlElement(name = "Associations")
    protected Associations associations;

    /**
     * Gets the value of the localID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalID() {
        return localID;
    }

    /**
     * Sets the value of the localID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalID(String value) {
        this.localID = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the repository property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepository() {
        return repository;
    }

    /**
     * Sets the value of the repository property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepository(String value) {
        this.repository = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the removalDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRemovalDate() {
        return removalDate;
    }

    /**
     * Sets the value of the removalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRemovalDate(XMLGregorianCalendar value) {
        this.removalDate = value;
    }

    /**
     * Gets the value of the license property.
     * 
     * @return
     *     possible object is
     *     {@link LicenseT }
     *     
     */
    public LicenseT getLicense() {
        return license;
    }

    /**
     * Sets the value of the license property.
     * 
     * @param value
     *     allowed object is
     *     {@link LicenseT }
     *     
     */
    public void setLicense(LicenseT value) {
        this.license = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the bestBenchmark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBestBenchmark() {
        return bestBenchmark;
    }

    /**
     * Sets the value of the bestBenchmark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBestBenchmark(String value) {
        this.bestBenchmark = value;
    }

    /**
     * Gets the value of the parallelSupport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParallelSupport() {
        return parallelSupport;
    }

    /**
     * Sets the value of the parallelSupport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParallelSupport(String value) {
        this.parallelSupport = value;
    }

    /**
     * Gets the value of the maxSlots property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxSlots() {
        return maxSlots;
    }

    /**
     * Sets the value of the maxSlots property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxSlots(Long value) {
        this.maxSlots = value;
    }

    /**
     * Gets the value of the maxJobs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxJobs() {
        return maxJobs;
    }

    /**
     * Sets the value of the maxJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxJobs(Long value) {
        this.maxJobs = value;
    }

    /**
     * Gets the value of the maxUserSeats property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxUserSeats() {
        return maxUserSeats;
    }

    /**
     * Sets the value of the maxUserSeats property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxUserSeats(Long value) {
        this.maxUserSeats = value;
    }

    /**
     * Gets the value of the freeSlots property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getFreeSlots() {
        return freeSlots;
    }

    /**
     * Sets the value of the freeSlots property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setFreeSlots(Long value) {
        this.freeSlots = value;
    }

    /**
     * Gets the value of the freeJobs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getFreeJobs() {
        return freeJobs;
    }

    /**
     * Sets the value of the freeJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setFreeJobs(Long value) {
        this.freeJobs = value;
    }

    /**
     * Gets the value of the freeUserSeats property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getFreeUserSeats() {
        return freeUserSeats;
    }

    /**
     * Sets the value of the freeUserSeats property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setFreeUserSeats(Long value) {
        this.freeUserSeats = value;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionsT }
     *     
     */
    public ExtensionsT getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionsT }
     *     
     */
    public void setExtensions(ExtensionsT value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the applicationHandle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicationHandle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicationHandle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicationHandleT }
     * 
     * 
     */
    public List<ApplicationHandleT> getApplicationHandle() {
        if (applicationHandle == null) {
            applicationHandle = new ArrayList<ApplicationHandleT>();
        }
        return this.applicationHandle;
    }

    /**
     * Gets the value of the associations property.
     * 
     * @return
     *     possible object is
     *     {@link Associations }
     *     
     */
    public Associations getAssociations() {
        return associations;
    }

    /**
     * Sets the value of the associations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Associations }
     *     
     */
    public void setAssociations(Associations value) {
        this.associations = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ExecutionEnvironmentLocalID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "executionEnvironmentLocalID"
    })
    public static class Associations {

        @XmlElement(name = "ExecutionEnvironmentLocalID", required = true)
        protected List<String> executionEnvironmentLocalID;

        /**
         * Gets the value of the executionEnvironmentLocalID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the executionEnvironmentLocalID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExecutionEnvironmentLocalID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getExecutionEnvironmentLocalID() {
            if (executionEnvironmentLocalID == null) {
                executionEnvironmentLocalID = new ArrayList<String>();
            }
            return this.executionEnvironmentLocalID;
        }

    }

}
