//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 05:26:33 PM CEST 
//


package com.terradue.ogf.schema.glue.impl;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.terradue.ogf.schema.glue.impl.ComputingShareT.Associations;


/**
 * <p>Java class for ComputingShare_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComputingShare_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}Share_t">
 *       &lt;sequence>
 *         &lt;element name="MappingQueue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaxWallTime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="MaxTotalWallTime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="MinWallTime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="DefaultWallTime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="MaxCPUTime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="MaxTotalCPUTime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="MaxCPUsTime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="MinCPUTime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="DefaultCPUTime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="MaxTotalJobs" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="MaxRunningJobs" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="MaxWaitingJobs" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="MaxPreLRMSWaitingJobs" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="MaxUserRunningJobs" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="MaxSlotsPerJob" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="MaxStateInStreams" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="MaxStageOutStreams" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="SchedulingPolicy" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}SchedulingPolicy_t" minOccurs="0"/>
 *         &lt;element name="MaxMemory" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="MaxDiskSpace" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="DefaultStorageService" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="Preemption" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ServingState" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ServingState_t"/>
 *         &lt;element name="TotalJobs" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="RunningJobs" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="LocalRunningJobs" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="WaitingJobs" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="LocalWaitingJobs" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="StagingJobs" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="SuspendedJobs" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="PreLRMSWaitingJobs" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="EstimatedAverageWaitingTime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="EstimatedWorstWaitingTime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="FreeSlots" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="FreeSlotsWithDuration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UsedSlots" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="RequestedSlots" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="ReservationPolicy" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ReservationPolicy_t" minOccurs="0"/>
 *         &lt;element name="Tag" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Extensions" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}Extensions_t" minOccurs="0"/>
 *         &lt;element name="MappingPolicy" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}MappingPolicy_t" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Associations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ComputingEndpointID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="ExecutionEnvironmentLocalID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="ComputingActivityID" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ID_t" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComputingShare_t", propOrder = {
    "mappingQueue",
    "maxWallTime",
    "maxTotalWallTime",
    "minWallTime",
    "defaultWallTime",
    "maxCPUTime",
    "maxTotalCPUTime",
    "maxCPUsTime",
    "minCPUTime",
    "defaultCPUTime",
    "maxTotalJobs",
    "maxRunningJobs",
    "maxWaitingJobs",
    "maxPreLRMSWaitingJobs",
    "maxUserRunningJobs",
    "maxSlotsPerJob",
    "maxStateInStreams",
    "maxStageOutStreams",
    "schedulingPolicy",
    "maxMemory",
    "maxDiskSpace",
    "defaultStorageService",
    "preemption",
    "servingState",
    "totalJobs",
    "runningJobs",
    "localRunningJobs",
    "waitingJobs",
    "localWaitingJobs",
    "stagingJobs",
    "suspendedJobs",
    "preLRMSWaitingJobs",
    "estimatedAverageWaitingTime",
    "estimatedWorstWaitingTime",
    "freeSlots",
    "freeSlotsWithDuration",
    "usedSlots",
    "requestedSlots",
    "reservationPolicy",
    "tag",
    "extensions",
    "mappingPolicy",
    "associations"
})
public class ComputingShareT
    extends ShareT
{

    @XmlElement(name = "MappingQueue")
    protected String mappingQueue;
    @XmlElement(name = "MaxWallTime")
    protected BigInteger maxWallTime;
    @XmlElement(name = "MaxTotalWallTime")
    protected BigInteger maxTotalWallTime;
    @XmlElement(name = "MinWallTime")
    protected BigInteger minWallTime;
    @XmlElement(name = "DefaultWallTime")
    protected BigInteger defaultWallTime;
    @XmlElement(name = "MaxCPUTime")
    protected BigInteger maxCPUTime;
    @XmlElement(name = "MaxTotalCPUTime")
    protected BigInteger maxTotalCPUTime;
    @XmlElement(name = "MaxCPUsTime")
    protected BigInteger maxCPUsTime;
    @XmlElement(name = "MinCPUTime")
    protected BigInteger minCPUTime;
    @XmlElement(name = "DefaultCPUTime")
    protected BigInteger defaultCPUTime;
    @XmlElement(name = "MaxTotalJobs")
    protected Long maxTotalJobs;
    @XmlElement(name = "MaxRunningJobs")
    protected Long maxRunningJobs;
    @XmlElement(name = "MaxWaitingJobs")
    protected Long maxWaitingJobs;
    @XmlElement(name = "MaxPreLRMSWaitingJobs")
    protected Long maxPreLRMSWaitingJobs;
    @XmlElement(name = "MaxUserRunningJobs")
    protected Long maxUserRunningJobs;
    @XmlElement(name = "MaxSlotsPerJob")
    protected Long maxSlotsPerJob;
    @XmlElement(name = "MaxStateInStreams")
    protected Long maxStateInStreams;
    @XmlElement(name = "MaxStageOutStreams")
    protected Long maxStageOutStreams;
    @XmlElement(name = "SchedulingPolicy")
    protected String schedulingPolicy;
    @XmlElement(name = "MaxMemory")
    protected BigInteger maxMemory;
    @XmlElement(name = "MaxDiskSpace")
    protected BigInteger maxDiskSpace;
    @XmlElement(name = "DefaultStorageService")
    protected String defaultStorageService;
    @XmlElement(name = "Preemption")
    protected Boolean preemption;
    @XmlElement(name = "ServingState", required = true)
    protected ServingStateT servingState;
    @XmlElement(name = "TotalJobs")
    protected Long totalJobs;
    @XmlElement(name = "RunningJobs")
    protected Long runningJobs;
    @XmlElement(name = "LocalRunningJobs")
    protected Long localRunningJobs;
    @XmlElement(name = "WaitingJobs")
    protected Long waitingJobs;
    @XmlElement(name = "LocalWaitingJobs")
    protected Long localWaitingJobs;
    @XmlElement(name = "StagingJobs")
    protected Long stagingJobs;
    @XmlElement(name = "SuspendedJobs")
    protected Long suspendedJobs;
    @XmlElement(name = "PreLRMSWaitingJobs")
    protected Long preLRMSWaitingJobs;
    @XmlElement(name = "EstimatedAverageWaitingTime")
    protected BigInteger estimatedAverageWaitingTime;
    @XmlElement(name = "EstimatedWorstWaitingTime")
    protected BigInteger estimatedWorstWaitingTime;
    @XmlElement(name = "FreeSlots")
    protected Long freeSlots;
    @XmlElement(name = "FreeSlotsWithDuration")
    protected String freeSlotsWithDuration;
    @XmlElement(name = "UsedSlots")
    protected Long usedSlots;
    @XmlElement(name = "RequestedSlots")
    protected Long requestedSlots;
    @XmlElement(name = "ReservationPolicy")
    protected ReservationPolicyT reservationPolicy;
    @XmlElement(name = "Tag", required = true)
    protected List<String> tag;
    @XmlElement(name = "Extensions")
    protected ExtensionsT extensions;
    @XmlElement(name = "MappingPolicy", required = true)
    protected List<MappingPolicyT> mappingPolicy;
    @XmlElement(name = "Associations")
    protected Associations associations;

    /**
     * Gets the value of the mappingQueue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMappingQueue() {
        return mappingQueue;
    }

    /**
     * Sets the value of the mappingQueue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMappingQueue(String value) {
        this.mappingQueue = value;
    }

    /**
     * Gets the value of the maxWallTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxWallTime() {
        return maxWallTime;
    }

    /**
     * Sets the value of the maxWallTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxWallTime(BigInteger value) {
        this.maxWallTime = value;
    }

    /**
     * Gets the value of the maxTotalWallTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxTotalWallTime() {
        return maxTotalWallTime;
    }

    /**
     * Sets the value of the maxTotalWallTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxTotalWallTime(BigInteger value) {
        this.maxTotalWallTime = value;
    }

    /**
     * Gets the value of the minWallTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinWallTime() {
        return minWallTime;
    }

    /**
     * Sets the value of the minWallTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinWallTime(BigInteger value) {
        this.minWallTime = value;
    }

    /**
     * Gets the value of the defaultWallTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDefaultWallTime() {
        return defaultWallTime;
    }

    /**
     * Sets the value of the defaultWallTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDefaultWallTime(BigInteger value) {
        this.defaultWallTime = value;
    }

    /**
     * Gets the value of the maxCPUTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxCPUTime() {
        return maxCPUTime;
    }

    /**
     * Sets the value of the maxCPUTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxCPUTime(BigInteger value) {
        this.maxCPUTime = value;
    }

    /**
     * Gets the value of the maxTotalCPUTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxTotalCPUTime() {
        return maxTotalCPUTime;
    }

    /**
     * Sets the value of the maxTotalCPUTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxTotalCPUTime(BigInteger value) {
        this.maxTotalCPUTime = value;
    }

    /**
     * Gets the value of the maxCPUsTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxCPUsTime() {
        return maxCPUsTime;
    }

    /**
     * Sets the value of the maxCPUsTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxCPUsTime(BigInteger value) {
        this.maxCPUsTime = value;
    }

    /**
     * Gets the value of the minCPUTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinCPUTime() {
        return minCPUTime;
    }

    /**
     * Sets the value of the minCPUTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinCPUTime(BigInteger value) {
        this.minCPUTime = value;
    }

    /**
     * Gets the value of the defaultCPUTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDefaultCPUTime() {
        return defaultCPUTime;
    }

    /**
     * Sets the value of the defaultCPUTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDefaultCPUTime(BigInteger value) {
        this.defaultCPUTime = value;
    }

    /**
     * Gets the value of the maxTotalJobs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxTotalJobs() {
        return maxTotalJobs;
    }

    /**
     * Sets the value of the maxTotalJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxTotalJobs(Long value) {
        this.maxTotalJobs = value;
    }

    /**
     * Gets the value of the maxRunningJobs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxRunningJobs() {
        return maxRunningJobs;
    }

    /**
     * Sets the value of the maxRunningJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxRunningJobs(Long value) {
        this.maxRunningJobs = value;
    }

    /**
     * Gets the value of the maxWaitingJobs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxWaitingJobs() {
        return maxWaitingJobs;
    }

    /**
     * Sets the value of the maxWaitingJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxWaitingJobs(Long value) {
        this.maxWaitingJobs = value;
    }

    /**
     * Gets the value of the maxPreLRMSWaitingJobs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxPreLRMSWaitingJobs() {
        return maxPreLRMSWaitingJobs;
    }

    /**
     * Sets the value of the maxPreLRMSWaitingJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxPreLRMSWaitingJobs(Long value) {
        this.maxPreLRMSWaitingJobs = value;
    }

    /**
     * Gets the value of the maxUserRunningJobs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxUserRunningJobs() {
        return maxUserRunningJobs;
    }

    /**
     * Sets the value of the maxUserRunningJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxUserRunningJobs(Long value) {
        this.maxUserRunningJobs = value;
    }

    /**
     * Gets the value of the maxSlotsPerJob property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxSlotsPerJob() {
        return maxSlotsPerJob;
    }

    /**
     * Sets the value of the maxSlotsPerJob property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxSlotsPerJob(Long value) {
        this.maxSlotsPerJob = value;
    }

    /**
     * Gets the value of the maxStateInStreams property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxStateInStreams() {
        return maxStateInStreams;
    }

    /**
     * Sets the value of the maxStateInStreams property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxStateInStreams(Long value) {
        this.maxStateInStreams = value;
    }

    /**
     * Gets the value of the maxStageOutStreams property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxStageOutStreams() {
        return maxStageOutStreams;
    }

    /**
     * Sets the value of the maxStageOutStreams property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxStageOutStreams(Long value) {
        this.maxStageOutStreams = value;
    }

    /**
     * Gets the value of the schedulingPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchedulingPolicy() {
        return schedulingPolicy;
    }

    /**
     * Sets the value of the schedulingPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchedulingPolicy(String value) {
        this.schedulingPolicy = value;
    }

    /**
     * Gets the value of the maxMemory property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxMemory() {
        return maxMemory;
    }

    /**
     * Sets the value of the maxMemory property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxMemory(BigInteger value) {
        this.maxMemory = value;
    }

    /**
     * Gets the value of the maxDiskSpace property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxDiskSpace() {
        return maxDiskSpace;
    }

    /**
     * Sets the value of the maxDiskSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxDiskSpace(BigInteger value) {
        this.maxDiskSpace = value;
    }

    /**
     * Gets the value of the defaultStorageService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultStorageService() {
        return defaultStorageService;
    }

    /**
     * Sets the value of the defaultStorageService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultStorageService(String value) {
        this.defaultStorageService = value;
    }

    /**
     * Gets the value of the preemption property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPreemption() {
        return preemption;
    }

    /**
     * Sets the value of the preemption property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPreemption(Boolean value) {
        this.preemption = value;
    }

    /**
     * Gets the value of the servingState property.
     * 
     * @return
     *     possible object is
     *     {@link ServingStateT }
     *     
     */
    public ServingStateT getServingState() {
        return servingState;
    }

    /**
     * Sets the value of the servingState property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServingStateT }
     *     
     */
    public void setServingState(ServingStateT value) {
        this.servingState = value;
    }

    /**
     * Gets the value of the totalJobs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTotalJobs() {
        return totalJobs;
    }

    /**
     * Sets the value of the totalJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTotalJobs(Long value) {
        this.totalJobs = value;
    }

    /**
     * Gets the value of the runningJobs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRunningJobs() {
        return runningJobs;
    }

    /**
     * Sets the value of the runningJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRunningJobs(Long value) {
        this.runningJobs = value;
    }

    /**
     * Gets the value of the localRunningJobs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLocalRunningJobs() {
        return localRunningJobs;
    }

    /**
     * Sets the value of the localRunningJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLocalRunningJobs(Long value) {
        this.localRunningJobs = value;
    }

    /**
     * Gets the value of the waitingJobs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getWaitingJobs() {
        return waitingJobs;
    }

    /**
     * Sets the value of the waitingJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setWaitingJobs(Long value) {
        this.waitingJobs = value;
    }

    /**
     * Gets the value of the localWaitingJobs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLocalWaitingJobs() {
        return localWaitingJobs;
    }

    /**
     * Sets the value of the localWaitingJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLocalWaitingJobs(Long value) {
        this.localWaitingJobs = value;
    }

    /**
     * Gets the value of the stagingJobs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStagingJobs() {
        return stagingJobs;
    }

    /**
     * Sets the value of the stagingJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStagingJobs(Long value) {
        this.stagingJobs = value;
    }

    /**
     * Gets the value of the suspendedJobs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSuspendedJobs() {
        return suspendedJobs;
    }

    /**
     * Sets the value of the suspendedJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSuspendedJobs(Long value) {
        this.suspendedJobs = value;
    }

    /**
     * Gets the value of the preLRMSWaitingJobs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPreLRMSWaitingJobs() {
        return preLRMSWaitingJobs;
    }

    /**
     * Sets the value of the preLRMSWaitingJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPreLRMSWaitingJobs(Long value) {
        this.preLRMSWaitingJobs = value;
    }

    /**
     * Gets the value of the estimatedAverageWaitingTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEstimatedAverageWaitingTime() {
        return estimatedAverageWaitingTime;
    }

    /**
     * Sets the value of the estimatedAverageWaitingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEstimatedAverageWaitingTime(BigInteger value) {
        this.estimatedAverageWaitingTime = value;
    }

    /**
     * Gets the value of the estimatedWorstWaitingTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEstimatedWorstWaitingTime() {
        return estimatedWorstWaitingTime;
    }

    /**
     * Sets the value of the estimatedWorstWaitingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEstimatedWorstWaitingTime(BigInteger value) {
        this.estimatedWorstWaitingTime = value;
    }

    /**
     * Gets the value of the freeSlots property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getFreeSlots() {
        return freeSlots;
    }

    /**
     * Sets the value of the freeSlots property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setFreeSlots(Long value) {
        this.freeSlots = value;
    }

    /**
     * Gets the value of the freeSlotsWithDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeSlotsWithDuration() {
        return freeSlotsWithDuration;
    }

    /**
     * Sets the value of the freeSlotsWithDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeSlotsWithDuration(String value) {
        this.freeSlotsWithDuration = value;
    }

    /**
     * Gets the value of the usedSlots property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getUsedSlots() {
        return usedSlots;
    }

    /**
     * Sets the value of the usedSlots property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUsedSlots(Long value) {
        this.usedSlots = value;
    }

    /**
     * Gets the value of the requestedSlots property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRequestedSlots() {
        return requestedSlots;
    }

    /**
     * Sets the value of the requestedSlots property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRequestedSlots(Long value) {
        this.requestedSlots = value;
    }

    /**
     * Gets the value of the reservationPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link ReservationPolicyT }
     *     
     */
    public ReservationPolicyT getReservationPolicy() {
        return reservationPolicy;
    }

    /**
     * Sets the value of the reservationPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReservationPolicyT }
     *     
     */
    public void setReservationPolicy(ReservationPolicyT value) {
        this.reservationPolicy = value;
    }

    /**
     * Gets the value of the tag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTag() {
        if (tag == null) {
            tag = new ArrayList<String>();
        }
        return this.tag;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionsT }
     *     
     */
    public ExtensionsT getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionsT }
     *     
     */
    public void setExtensions(ExtensionsT value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the mappingPolicy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mappingPolicy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMappingPolicy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MappingPolicyT }
     * 
     * 
     */
    public List<MappingPolicyT> getMappingPolicy() {
        if (mappingPolicy == null) {
            mappingPolicy = new ArrayList<MappingPolicyT>();
        }
        return this.mappingPolicy;
    }

    /**
     * Gets the value of the associations property.
     * 
     * @return
     *     possible object is
     *     {@link Associations }
     *     
     */
    public Associations getAssociations() {
        return associations;
    }

    /**
     * Sets the value of the associations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Associations }
     *     
     */
    public void setAssociations(Associations value) {
        this.associations = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ComputingEndpointID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="ExecutionEnvironmentLocalID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="ComputingActivityID" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ID_t" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "computingEndpointID",
        "executionEnvironmentLocalID",
        "computingActivityID"
    })
    public static class Associations {

        @XmlElement(name = "ComputingEndpointID", required = true)
        protected List<String> computingEndpointID;
        @XmlElement(name = "ExecutionEnvironmentLocalID", required = true)
        protected List<String> executionEnvironmentLocalID;
        @XmlElement(name = "ComputingActivityID", required = true)
        protected List<String> computingActivityID;

        /**
         * Gets the value of the computingEndpointID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the computingEndpointID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getComputingEndpointID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getComputingEndpointID() {
            if (computingEndpointID == null) {
                computingEndpointID = new ArrayList<String>();
            }
            return this.computingEndpointID;
        }

        /**
         * Gets the value of the executionEnvironmentLocalID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the executionEnvironmentLocalID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExecutionEnvironmentLocalID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getExecutionEnvironmentLocalID() {
            if (executionEnvironmentLocalID == null) {
                executionEnvironmentLocalID = new ArrayList<String>();
            }
            return this.executionEnvironmentLocalID;
        }

        /**
         * Gets the value of the computingActivityID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the computingActivityID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getComputingActivityID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getComputingActivityID() {
            if (computingActivityID == null) {
                computingActivityID = new ArrayList<String>();
            }
            return this.computingActivityID;
        }

    }

}
