//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 05:26:33 PM CEST 
//


package com.terradue.ogf.schema.glue.impl;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.terradue.ogf.schema.glue.impl.ComputingActivityT.Associations;


/**
 * <p>Java class for ComputingActivity_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComputingActivity_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ActivityProperties_t">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Type" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ComputingActivityType_t" minOccurs="0"/>
 *         &lt;element name="IDFromEndpoint" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="LocalIDFromManager" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="JobDescription" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}JobDescription_t"/>
 *         &lt;element name="State" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ComputingActivityState_t"/>
 *         &lt;element name="RestartState" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ComputingActivityState_t" minOccurs="0"/>
 *         &lt;element name="ExitCode" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ComputingManagerExitCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Error" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="WaitingPosition" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="UserDomain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Owner" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LocalOwner" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RequestedTotalWallTime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="RequestedTotalCPUTime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="RequestedSlots" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="RequestedApplicationEnvironment" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StdIn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StdOut" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StdErr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LogDir" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExecutionNode" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Queue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UsedTotalWallTime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="UsedTotalCPUTime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="UsedMainMemory" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="SubmissionTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ComputingManagerSubmissionTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ComputingManagerEndTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="EndTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="WorkingAreaEraseTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ProxyExpirationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="SubmissionHost" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SubmissionClientName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OtherMessages" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Extensions" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}Extensions_t" minOccurs="0"/>
 *         &lt;element name="Associations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ComputingEndpointID" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *                   &lt;element name="ComputingShareLocalID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ExecutionEnvironmentLocalID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="UserDomainID" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *                   &lt;element name="ActivityID" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComputingActivity_t", propOrder = {
    "name",
    "type",
    "idFromEndpoint",
    "localIDFromManager",
    "jobDescription",
    "state",
    "restartState",
    "exitCode",
    "computingManagerExitCode",
    "error",
    "waitingPosition",
    "userDomain",
    "owner",
    "localOwner",
    "requestedTotalWallTime",
    "requestedTotalCPUTime",
    "requestedSlots",
    "requestedApplicationEnvironment",
    "stdIn",
    "stdOut",
    "stdErr",
    "logDir",
    "executionNode",
    "queue",
    "usedTotalWallTime",
    "usedTotalCPUTime",
    "usedMainMemory",
    "submissionTime",
    "computingManagerSubmissionTime",
    "startTime",
    "computingManagerEndTime",
    "endTime",
    "workingAreaEraseTime",
    "proxyExpirationTime",
    "submissionHost",
    "submissionClientName",
    "otherMessages",
    "extensions",
    "associations"
})
public class ComputingActivityT
    extends ActivityPropertiesT
{

    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Type")
    protected ComputingActivityTypeT type;
    @XmlElement(name = "IDFromEndpoint", required = true)
    protected String idFromEndpoint;
    @XmlElement(name = "LocalIDFromManager")
    protected String localIDFromManager;
    @XmlElement(name = "JobDescription", required = true)
    protected String jobDescription;
    @XmlElement(name = "State", required = true)
    protected String state;
    @XmlElement(name = "RestartState")
    protected String restartState;
    @XmlElement(name = "ExitCode")
    protected Integer exitCode;
    @XmlElement(name = "ComputingManagerExitCode")
    protected String computingManagerExitCode;
    @XmlElement(name = "Error", required = true)
    protected List<String> error;
    @XmlElement(name = "WaitingPosition")
    protected Long waitingPosition;
    @XmlElement(name = "UserDomain")
    protected String userDomain;
    @XmlElement(name = "Owner", required = true)
    protected String owner;
    @XmlElement(name = "LocalOwner")
    protected String localOwner;
    @XmlElement(name = "RequestedTotalWallTime")
    protected BigInteger requestedTotalWallTime;
    @XmlElement(name = "RequestedTotalCPUTime")
    protected BigInteger requestedTotalCPUTime;
    @XmlElement(name = "RequestedSlots")
    protected Long requestedSlots;
    @XmlElement(name = "RequestedApplicationEnvironment", required = true)
    protected List<String> requestedApplicationEnvironment;
    @XmlElement(name = "StdIn")
    protected String stdIn;
    @XmlElement(name = "StdOut")
    protected String stdOut;
    @XmlElement(name = "StdErr")
    protected String stdErr;
    @XmlElement(name = "LogDir")
    protected String logDir;
    @XmlElement(name = "ExecutionNode", required = true)
    protected List<String> executionNode;
    @XmlElement(name = "Queue")
    protected String queue;
    @XmlElement(name = "UsedTotalWallTime")
    protected BigInteger usedTotalWallTime;
    @XmlElement(name = "UsedTotalCPUTime")
    protected BigInteger usedTotalCPUTime;
    @XmlElement(name = "UsedMainMemory")
    protected BigInteger usedMainMemory;
    @XmlElement(name = "SubmissionTime")
    protected XMLGregorianCalendar submissionTime;
    @XmlElement(name = "ComputingManagerSubmissionTime")
    protected XMLGregorianCalendar computingManagerSubmissionTime;
    @XmlElement(name = "StartTime")
    protected XMLGregorianCalendar startTime;
    @XmlElement(name = "ComputingManagerEndTime")
    protected XMLGregorianCalendar computingManagerEndTime;
    @XmlElement(name = "EndTime")
    protected XMLGregorianCalendar endTime;
    @XmlElement(name = "WorkingAreaEraseTime")
    protected XMLGregorianCalendar workingAreaEraseTime;
    @XmlElement(name = "ProxyExpirationTime")
    protected XMLGregorianCalendar proxyExpirationTime;
    @XmlElement(name = "SubmissionHost")
    protected String submissionHost;
    @XmlElement(name = "SubmissionClientName")
    protected String submissionClientName;
    @XmlElement(name = "OtherMessages", required = true)
    protected List<String> otherMessages;
    @XmlElement(name = "Extensions")
    protected ExtensionsT extensions;
    @XmlElement(name = "Associations")
    protected Associations associations;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ComputingActivityTypeT }
     *     
     */
    public ComputingActivityTypeT getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComputingActivityTypeT }
     *     
     */
    public void setType(ComputingActivityTypeT value) {
        this.type = value;
    }

    /**
     * Gets the value of the idFromEndpoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDFromEndpoint() {
        return idFromEndpoint;
    }

    /**
     * Sets the value of the idFromEndpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDFromEndpoint(String value) {
        this.idFromEndpoint = value;
    }

    /**
     * Gets the value of the localIDFromManager property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalIDFromManager() {
        return localIDFromManager;
    }

    /**
     * Sets the value of the localIDFromManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalIDFromManager(String value) {
        this.localIDFromManager = value;
    }

    /**
     * Gets the value of the jobDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobDescription() {
        return jobDescription;
    }

    /**
     * Sets the value of the jobDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobDescription(String value) {
        this.jobDescription = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the restartState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestartState() {
        return restartState;
    }

    /**
     * Sets the value of the restartState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestartState(String value) {
        this.restartState = value;
    }

    /**
     * Gets the value of the exitCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExitCode() {
        return exitCode;
    }

    /**
     * Sets the value of the exitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExitCode(Integer value) {
        this.exitCode = value;
    }

    /**
     * Gets the value of the computingManagerExitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComputingManagerExitCode() {
        return computingManagerExitCode;
    }

    /**
     * Sets the value of the computingManagerExitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComputingManagerExitCode(String value) {
        this.computingManagerExitCode = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the error property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getError().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getError() {
        if (error == null) {
            error = new ArrayList<String>();
        }
        return this.error;
    }

    /**
     * Gets the value of the waitingPosition property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getWaitingPosition() {
        return waitingPosition;
    }

    /**
     * Sets the value of the waitingPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setWaitingPosition(Long value) {
        this.waitingPosition = value;
    }

    /**
     * Gets the value of the userDomain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDomain() {
        return userDomain;
    }

    /**
     * Sets the value of the userDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDomain(String value) {
        this.userDomain = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the localOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalOwner() {
        return localOwner;
    }

    /**
     * Sets the value of the localOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalOwner(String value) {
        this.localOwner = value;
    }

    /**
     * Gets the value of the requestedTotalWallTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRequestedTotalWallTime() {
        return requestedTotalWallTime;
    }

    /**
     * Sets the value of the requestedTotalWallTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRequestedTotalWallTime(BigInteger value) {
        this.requestedTotalWallTime = value;
    }

    /**
     * Gets the value of the requestedTotalCPUTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRequestedTotalCPUTime() {
        return requestedTotalCPUTime;
    }

    /**
     * Sets the value of the requestedTotalCPUTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRequestedTotalCPUTime(BigInteger value) {
        this.requestedTotalCPUTime = value;
    }

    /**
     * Gets the value of the requestedSlots property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRequestedSlots() {
        return requestedSlots;
    }

    /**
     * Sets the value of the requestedSlots property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRequestedSlots(Long value) {
        this.requestedSlots = value;
    }

    /**
     * Gets the value of the requestedApplicationEnvironment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requestedApplicationEnvironment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequestedApplicationEnvironment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRequestedApplicationEnvironment() {
        if (requestedApplicationEnvironment == null) {
            requestedApplicationEnvironment = new ArrayList<String>();
        }
        return this.requestedApplicationEnvironment;
    }

    /**
     * Gets the value of the stdIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStdIn() {
        return stdIn;
    }

    /**
     * Sets the value of the stdIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStdIn(String value) {
        this.stdIn = value;
    }

    /**
     * Gets the value of the stdOut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStdOut() {
        return stdOut;
    }

    /**
     * Sets the value of the stdOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStdOut(String value) {
        this.stdOut = value;
    }

    /**
     * Gets the value of the stdErr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStdErr() {
        return stdErr;
    }

    /**
     * Sets the value of the stdErr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStdErr(String value) {
        this.stdErr = value;
    }

    /**
     * Gets the value of the logDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogDir() {
        return logDir;
    }

    /**
     * Sets the value of the logDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogDir(String value) {
        this.logDir = value;
    }

    /**
     * Gets the value of the executionNode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the executionNode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExecutionNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getExecutionNode() {
        if (executionNode == null) {
            executionNode = new ArrayList<String>();
        }
        return this.executionNode;
    }

    /**
     * Gets the value of the queue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueue() {
        return queue;
    }

    /**
     * Sets the value of the queue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueue(String value) {
        this.queue = value;
    }

    /**
     * Gets the value of the usedTotalWallTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUsedTotalWallTime() {
        return usedTotalWallTime;
    }

    /**
     * Sets the value of the usedTotalWallTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUsedTotalWallTime(BigInteger value) {
        this.usedTotalWallTime = value;
    }

    /**
     * Gets the value of the usedTotalCPUTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUsedTotalCPUTime() {
        return usedTotalCPUTime;
    }

    /**
     * Sets the value of the usedTotalCPUTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUsedTotalCPUTime(BigInteger value) {
        this.usedTotalCPUTime = value;
    }

    /**
     * Gets the value of the usedMainMemory property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUsedMainMemory() {
        return usedMainMemory;
    }

    /**
     * Sets the value of the usedMainMemory property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUsedMainMemory(BigInteger value) {
        this.usedMainMemory = value;
    }

    /**
     * Gets the value of the submissionTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSubmissionTime() {
        return submissionTime;
    }

    /**
     * Sets the value of the submissionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSubmissionTime(XMLGregorianCalendar value) {
        this.submissionTime = value;
    }

    /**
     * Gets the value of the computingManagerSubmissionTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getComputingManagerSubmissionTime() {
        return computingManagerSubmissionTime;
    }

    /**
     * Sets the value of the computingManagerSubmissionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setComputingManagerSubmissionTime(XMLGregorianCalendar value) {
        this.computingManagerSubmissionTime = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTime(XMLGregorianCalendar value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the computingManagerEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getComputingManagerEndTime() {
        return computingManagerEndTime;
    }

    /**
     * Sets the value of the computingManagerEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setComputingManagerEndTime(XMLGregorianCalendar value) {
        this.computingManagerEndTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndTime(XMLGregorianCalendar value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the workingAreaEraseTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getWorkingAreaEraseTime() {
        return workingAreaEraseTime;
    }

    /**
     * Sets the value of the workingAreaEraseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setWorkingAreaEraseTime(XMLGregorianCalendar value) {
        this.workingAreaEraseTime = value;
    }

    /**
     * Gets the value of the proxyExpirationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProxyExpirationTime() {
        return proxyExpirationTime;
    }

    /**
     * Sets the value of the proxyExpirationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProxyExpirationTime(XMLGregorianCalendar value) {
        this.proxyExpirationTime = value;
    }

    /**
     * Gets the value of the submissionHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubmissionHost() {
        return submissionHost;
    }

    /**
     * Sets the value of the submissionHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubmissionHost(String value) {
        this.submissionHost = value;
    }

    /**
     * Gets the value of the submissionClientName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubmissionClientName() {
        return submissionClientName;
    }

    /**
     * Sets the value of the submissionClientName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubmissionClientName(String value) {
        this.submissionClientName = value;
    }

    /**
     * Gets the value of the otherMessages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherMessages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherMessages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOtherMessages() {
        if (otherMessages == null) {
            otherMessages = new ArrayList<String>();
        }
        return this.otherMessages;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionsT }
     *     
     */
    public ExtensionsT getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionsT }
     *     
     */
    public void setExtensions(ExtensionsT value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the associations property.
     * 
     * @return
     *     possible object is
     *     {@link Associations }
     *     
     */
    public Associations getAssociations() {
        return associations;
    }

    /**
     * Sets the value of the associations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Associations }
     *     
     */
    public void setAssociations(Associations value) {
        this.associations = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ComputingEndpointID" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
     *         &lt;element name="ComputingShareLocalID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ExecutionEnvironmentLocalID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="UserDomainID" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
     *         &lt;element name="ActivityID" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "computingEndpointID",
        "computingShareLocalID",
        "executionEnvironmentLocalID",
        "userDomainID",
        "activityID"
    })
    public static class Associations {

        @XmlElement(name = "ComputingEndpointID")
        protected String computingEndpointID;
        @XmlElement(name = "ComputingShareLocalID")
        protected String computingShareLocalID;
        @XmlElement(name = "ExecutionEnvironmentLocalID")
        protected String executionEnvironmentLocalID;
        @XmlElement(name = "UserDomainID")
        protected String userDomainID;
        @XmlElement(name = "ActivityID", required = true)
        protected List<String> activityID;

        /**
         * Gets the value of the computingEndpointID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComputingEndpointID() {
            return computingEndpointID;
        }

        /**
         * Sets the value of the computingEndpointID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComputingEndpointID(String value) {
            this.computingEndpointID = value;
        }

        /**
         * Gets the value of the computingShareLocalID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComputingShareLocalID() {
            return computingShareLocalID;
        }

        /**
         * Sets the value of the computingShareLocalID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComputingShareLocalID(String value) {
            this.computingShareLocalID = value;
        }

        /**
         * Gets the value of the executionEnvironmentLocalID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExecutionEnvironmentLocalID() {
            return executionEnvironmentLocalID;
        }

        /**
         * Sets the value of the executionEnvironmentLocalID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExecutionEnvironmentLocalID(String value) {
            this.executionEnvironmentLocalID = value;
        }

        /**
         * Gets the value of the userDomainID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserDomainID() {
            return userDomainID;
        }

        /**
         * Sets the value of the userDomainID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserDomainID(String value) {
            this.userDomainID = value;
        }

        /**
         * Gets the value of the activityID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the activityID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getActivityID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getActivityID() {
            if (activityID == null) {
                activityID = new ArrayList<String>();
            }
            return this.activityID;
        }

    }

}
