//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 05:26:33 PM CEST 
//


package com.terradue.ogf.schema.glue.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Domains_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Domains_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}Entity">
 *       &lt;sequence>
 *         &lt;element name="AdminDomain" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}AdminDomain_t" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UserDomain" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}UserDomain_t" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Domains_t", propOrder = {
    "adminDomain",
    "userDomain"
})
public class DomainsT
    extends Entity
{

    @XmlElement(name = "AdminDomain", required = true)
    protected List<AdminDomainT> adminDomain;
    @XmlElement(name = "UserDomain", required = true)
    protected List<UserDomainT> userDomain;

    /**
     * Gets the value of the adminDomain property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adminDomain property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdminDomain().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminDomainT }
     * 
     * 
     */
    public List<AdminDomainT> getAdminDomain() {
        if (adminDomain == null) {
            adminDomain = new ArrayList<AdminDomainT>();
        }
        return this.adminDomain;
    }

    /**
     * Gets the value of the userDomain property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userDomain property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserDomain().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserDomainT }
     * 
     * 
     */
    public List<UserDomainT> getUserDomain() {
        if (userDomain == null) {
            userDomain = new ArrayList<UserDomainT>();
        }
        return this.userDomain;
    }

}
