//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 05:26:33 PM CEST 
//


package com.terradue.ogf.schema.glue.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for EndpointProperties_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EndpointProperties_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}Entity">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ID_t"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="Capability" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}Capability_t" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Technology" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}EndpointTechnology_t"/>
 *         &lt;element name="Interface" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="InterfaceExtension" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="WSDL" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SupportedProfile" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Semantics" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Implementor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ImplementationName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ImplementationVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="QualityLevel" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}QualityLevel_t"/>
 *         &lt;element name="HealthState" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}EndpointHealthState_t"/>
 *         &lt;element name="HealthStateInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ServingState" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ServingState_t"/>
 *         &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="IssuerCA" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}DN_t" minOccurs="0"/>
 *         &lt;element name="TrustedCA" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}DN_t" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DowntimeAnnounce" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="DowntimeStart" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="DowntimeEnd" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="DowntimeInfo" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="BaseType" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="Endpoint" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EndpointProperties_t", propOrder = {
    "id",
    "name",
    "url",
    "capability",
    "technology",
    "_interface",
    "interfaceExtension",
    "wsdl",
    "supportedProfile",
    "semantics",
    "implementor",
    "implementationName",
    "implementationVersion",
    "qualityLevel",
    "healthState",
    "healthStateInfo",
    "servingState",
    "startTime",
    "issuerCA",
    "trustedCA",
    "downtimeAnnounce",
    "downtimeStart",
    "downtimeEnd",
    "downtimeInfo"
})
public class EndpointPropertiesT
    extends Entity
{

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "URL", required = true)
    protected String url;
    @XmlElement(name = "Capability", required = true)
    protected List<CapabilityT> capability;
    @XmlElement(name = "Technology", required = true)
    protected String technology;
    @XmlElement(name = "Interface")
    protected String _interface;
    @XmlElement(name = "InterfaceExtension", required = true)
    protected List<String> interfaceExtension;
    @XmlElement(name = "WSDL", required = true)
    protected List<String> wsdl;
    @XmlElement(name = "SupportedProfile", required = true)
    protected List<String> supportedProfile;
    @XmlElement(name = "Semantics", required = true)
    protected List<String> semantics;
    @XmlElement(name = "Implementor")
    protected String implementor;
    @XmlElement(name = "ImplementationName")
    protected String implementationName;
    @XmlElement(name = "ImplementationVersion")
    protected String implementationVersion;
    @XmlElement(name = "QualityLevel", required = true)
    protected QualityLevelT qualityLevel;
    @XmlElement(name = "HealthState", required = true)
    protected EndpointHealthStateT healthState;
    @XmlElement(name = "HealthStateInfo")
    protected String healthStateInfo;
    @XmlElement(name = "ServingState", required = true)
    protected ServingStateT servingState;
    @XmlElement(name = "StartTime")
    protected XMLGregorianCalendar startTime;
    @XmlElement(name = "IssuerCA")
    protected String issuerCA;
    @XmlElement(name = "TrustedCA", required = true)
    protected List<String> trustedCA;
    @XmlElement(name = "DowntimeAnnounce")
    protected XMLGregorianCalendar downtimeAnnounce;
    @XmlElement(name = "DowntimeStart")
    protected XMLGregorianCalendar downtimeStart;
    @XmlElement(name = "DowntimeEnd")
    protected XMLGregorianCalendar downtimeEnd;
    @XmlElement(name = "DowntimeInfo", required = true)
    protected List<String> downtimeInfo;
    @XmlAttribute(name = "BaseType", required = true)
    protected String baseType;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURL(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the capability property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the capability property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCapability().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CapabilityT }
     * 
     * 
     */
    public List<CapabilityT> getCapability() {
        if (capability == null) {
            capability = new ArrayList<CapabilityT>();
        }
        return this.capability;
    }

    /**
     * Gets the value of the technology property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnology() {
        return technology;
    }

    /**
     * Sets the value of the technology property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnology(String value) {
        this.technology = value;
    }

    /**
     * Gets the value of the interface property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterface() {
        return _interface;
    }

    /**
     * Sets the value of the interface property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterface(String value) {
        this._interface = value;
    }

    /**
     * Gets the value of the interfaceExtension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interfaceExtension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterfaceExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getInterfaceExtension() {
        if (interfaceExtension == null) {
            interfaceExtension = new ArrayList<String>();
        }
        return this.interfaceExtension;
    }

    /**
     * Gets the value of the wsdl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wsdl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWSDL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getWSDL() {
        if (wsdl == null) {
            wsdl = new ArrayList<String>();
        }
        return this.wsdl;
    }

    /**
     * Gets the value of the supportedProfile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportedProfile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportedProfile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSupportedProfile() {
        if (supportedProfile == null) {
            supportedProfile = new ArrayList<String>();
        }
        return this.supportedProfile;
    }

    /**
     * Gets the value of the semantics property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the semantics property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSemantics().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSemantics() {
        if (semantics == null) {
            semantics = new ArrayList<String>();
        }
        return this.semantics;
    }

    /**
     * Gets the value of the implementor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImplementor() {
        return implementor;
    }

    /**
     * Sets the value of the implementor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplementor(String value) {
        this.implementor = value;
    }

    /**
     * Gets the value of the implementationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImplementationName() {
        return implementationName;
    }

    /**
     * Sets the value of the implementationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplementationName(String value) {
        this.implementationName = value;
    }

    /**
     * Gets the value of the implementationVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImplementationVersion() {
        return implementationVersion;
    }

    /**
     * Sets the value of the implementationVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplementationVersion(String value) {
        this.implementationVersion = value;
    }

    /**
     * Gets the value of the qualityLevel property.
     * 
     * @return
     *     possible object is
     *     {@link QualityLevelT }
     *     
     */
    public QualityLevelT getQualityLevel() {
        return qualityLevel;
    }

    /**
     * Sets the value of the qualityLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualityLevelT }
     *     
     */
    public void setQualityLevel(QualityLevelT value) {
        this.qualityLevel = value;
    }

    /**
     * Gets the value of the healthState property.
     * 
     * @return
     *     possible object is
     *     {@link EndpointHealthStateT }
     *     
     */
    public EndpointHealthStateT getHealthState() {
        return healthState;
    }

    /**
     * Sets the value of the healthState property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndpointHealthStateT }
     *     
     */
    public void setHealthState(EndpointHealthStateT value) {
        this.healthState = value;
    }

    /**
     * Gets the value of the healthStateInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHealthStateInfo() {
        return healthStateInfo;
    }

    /**
     * Sets the value of the healthStateInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHealthStateInfo(String value) {
        this.healthStateInfo = value;
    }

    /**
     * Gets the value of the servingState property.
     * 
     * @return
     *     possible object is
     *     {@link ServingStateT }
     *     
     */
    public ServingStateT getServingState() {
        return servingState;
    }

    /**
     * Sets the value of the servingState property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServingStateT }
     *     
     */
    public void setServingState(ServingStateT value) {
        this.servingState = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTime(XMLGregorianCalendar value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the issuerCA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerCA() {
        return issuerCA;
    }

    /**
     * Sets the value of the issuerCA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerCA(String value) {
        this.issuerCA = value;
    }

    /**
     * Gets the value of the trustedCA property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trustedCA property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrustedCA().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTrustedCA() {
        if (trustedCA == null) {
            trustedCA = new ArrayList<String>();
        }
        return this.trustedCA;
    }

    /**
     * Gets the value of the downtimeAnnounce property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDowntimeAnnounce() {
        return downtimeAnnounce;
    }

    /**
     * Sets the value of the downtimeAnnounce property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDowntimeAnnounce(XMLGregorianCalendar value) {
        this.downtimeAnnounce = value;
    }

    /**
     * Gets the value of the downtimeStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDowntimeStart() {
        return downtimeStart;
    }

    /**
     * Sets the value of the downtimeStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDowntimeStart(XMLGregorianCalendar value) {
        this.downtimeStart = value;
    }

    /**
     * Gets the value of the downtimeEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDowntimeEnd() {
        return downtimeEnd;
    }

    /**
     * Sets the value of the downtimeEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDowntimeEnd(XMLGregorianCalendar value) {
        this.downtimeEnd = value;
    }

    /**
     * Gets the value of the downtimeInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the downtimeInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDowntimeInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDowntimeInfo() {
        if (downtimeInfo == null) {
            downtimeInfo = new ArrayList<String>();
        }
        return this.downtimeInfo;
    }

    /**
     * Gets the value of the baseType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseType() {
        if (baseType == null) {
            return "Endpoint";
        } else {
            return baseType;
        }
    }

    /**
     * Sets the value of the baseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseType(String value) {
        this.baseType = value;
    }

}
