//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 05:26:33 PM CEST 
//


package com.terradue.ogf.schema.glue.impl;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.terradue.ogf.schema.glue.impl.ExecutionEnvironmentT.Associations;


/**
 * <p>Java class for ExecutionEnvironment_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExecutionEnvironment_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}Resource_t">
 *       &lt;sequence>
 *         &lt;element name="Platform" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}Platform_t"/>
 *         &lt;element name="VirtualMachine" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="TotalInstances" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="UsedInstances" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="UnavailableInstances" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="PhysicalCPUs" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="LogicalCPUs" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="CPUMultiplicity" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}CPUMultiplicity_t" minOccurs="0"/>
 *         &lt;element name="CPUVendor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CPUModel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CPUVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CPUClockSpeed" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="CPUTimeScalingFactor" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="WallTimeScalingFactor" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="MainMemorySize" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="VirtualMemorySize" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="OSFamily" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}OSFamily_t" minOccurs="0"/>
 *         &lt;element name="OSName" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}OSName_t" minOccurs="0"/>
 *         &lt;element name="OSVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ConnectivityIn" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ConnectivityOut" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="NetworkInfo" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}NetworkInfo_t" minOccurs="0"/>
 *         &lt;element name="Extensions" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}Extensions_t" minOccurs="0"/>
 *         &lt;element name="Benchmark" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}Benchmark_t" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Associations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ComputingShareLocalID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="ApplicationEnvironmentLocalID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="ComputingActivityID" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ID_t" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExecutionEnvironment_t", propOrder = {
    "platform",
    "virtualMachine",
    "totalInstances",
    "usedInstances",
    "unavailableInstances",
    "physicalCPUs",
    "logicalCPUs",
    "cpuMultiplicity",
    "cpuVendor",
    "cpuModel",
    "cpuVersion",
    "cpuClockSpeed",
    "cpuTimeScalingFactor",
    "wallTimeScalingFactor",
    "mainMemorySize",
    "virtualMemorySize",
    "osFamily",
    "osName",
    "osVersion",
    "connectivityIn",
    "connectivityOut",
    "networkInfo",
    "extensions",
    "benchmark",
    "associations"
})
public class ExecutionEnvironmentT
    extends ResourceT
{

    @XmlElement(name = "Platform", required = true)
    protected String platform;
    @XmlElement(name = "VirtualMachine")
    protected Boolean virtualMachine;
    @XmlElement(name = "TotalInstances")
    protected Long totalInstances;
    @XmlElement(name = "UsedInstances")
    protected Long usedInstances;
    @XmlElement(name = "UnavailableInstances")
    protected Long unavailableInstances;
    @XmlElement(name = "PhysicalCPUs")
    protected Long physicalCPUs;
    @XmlElement(name = "LogicalCPUs")
    protected Long logicalCPUs;
    @XmlElement(name = "CPUMultiplicity")
    protected CPUMultiplicityT cpuMultiplicity;
    @XmlElement(name = "CPUVendor")
    protected String cpuVendor;
    @XmlElement(name = "CPUModel")
    protected String cpuModel;
    @XmlElement(name = "CPUVersion")
    protected String cpuVersion;
    @XmlElement(name = "CPUClockSpeed")
    protected Long cpuClockSpeed;
    @XmlElement(name = "CPUTimeScalingFactor")
    protected Float cpuTimeScalingFactor;
    @XmlElement(name = "WallTimeScalingFactor")
    protected Float wallTimeScalingFactor;
    @XmlElement(name = "MainMemorySize")
    protected BigInteger mainMemorySize;
    @XmlElement(name = "VirtualMemorySize")
    protected BigInteger virtualMemorySize;
    @XmlElement(name = "OSFamily")
    protected String osFamily;
    @XmlElement(name = "OSName")
    protected String osName;
    @XmlElement(name = "OSVersion")
    protected String osVersion;
    @XmlElement(name = "ConnectivityIn")
    protected Boolean connectivityIn;
    @XmlElement(name = "ConnectivityOut")
    protected Boolean connectivityOut;
    @XmlElement(name = "NetworkInfo")
    protected String networkInfo;
    @XmlElement(name = "Extensions")
    protected ExtensionsT extensions;
    @XmlElement(name = "Benchmark", required = true)
    protected List<BenchmarkT> benchmark;
    @XmlElement(name = "Associations")
    protected Associations associations;

    /**
     * Gets the value of the platform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * Sets the value of the platform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatform(String value) {
        this.platform = value;
    }

    /**
     * Gets the value of the virtualMachine property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVirtualMachine() {
        return virtualMachine;
    }

    /**
     * Sets the value of the virtualMachine property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVirtualMachine(Boolean value) {
        this.virtualMachine = value;
    }

    /**
     * Gets the value of the totalInstances property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTotalInstances() {
        return totalInstances;
    }

    /**
     * Sets the value of the totalInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTotalInstances(Long value) {
        this.totalInstances = value;
    }

    /**
     * Gets the value of the usedInstances property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getUsedInstances() {
        return usedInstances;
    }

    /**
     * Sets the value of the usedInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUsedInstances(Long value) {
        this.usedInstances = value;
    }

    /**
     * Gets the value of the unavailableInstances property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getUnavailableInstances() {
        return unavailableInstances;
    }

    /**
     * Sets the value of the unavailableInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUnavailableInstances(Long value) {
        this.unavailableInstances = value;
    }

    /**
     * Gets the value of the physicalCPUs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPhysicalCPUs() {
        return physicalCPUs;
    }

    /**
     * Sets the value of the physicalCPUs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPhysicalCPUs(Long value) {
        this.physicalCPUs = value;
    }

    /**
     * Gets the value of the logicalCPUs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLogicalCPUs() {
        return logicalCPUs;
    }

    /**
     * Sets the value of the logicalCPUs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLogicalCPUs(Long value) {
        this.logicalCPUs = value;
    }

    /**
     * Gets the value of the cpuMultiplicity property.
     * 
     * @return
     *     possible object is
     *     {@link CPUMultiplicityT }
     *     
     */
    public CPUMultiplicityT getCPUMultiplicity() {
        return cpuMultiplicity;
    }

    /**
     * Sets the value of the cpuMultiplicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CPUMultiplicityT }
     *     
     */
    public void setCPUMultiplicity(CPUMultiplicityT value) {
        this.cpuMultiplicity = value;
    }

    /**
     * Gets the value of the cpuVendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPUVendor() {
        return cpuVendor;
    }

    /**
     * Sets the value of the cpuVendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPUVendor(String value) {
        this.cpuVendor = value;
    }

    /**
     * Gets the value of the cpuModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPUModel() {
        return cpuModel;
    }

    /**
     * Sets the value of the cpuModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPUModel(String value) {
        this.cpuModel = value;
    }

    /**
     * Gets the value of the cpuVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPUVersion() {
        return cpuVersion;
    }

    /**
     * Sets the value of the cpuVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPUVersion(String value) {
        this.cpuVersion = value;
    }

    /**
     * Gets the value of the cpuClockSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCPUClockSpeed() {
        return cpuClockSpeed;
    }

    /**
     * Sets the value of the cpuClockSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCPUClockSpeed(Long value) {
        this.cpuClockSpeed = value;
    }

    /**
     * Gets the value of the cpuTimeScalingFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getCPUTimeScalingFactor() {
        return cpuTimeScalingFactor;
    }

    /**
     * Sets the value of the cpuTimeScalingFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCPUTimeScalingFactor(Float value) {
        this.cpuTimeScalingFactor = value;
    }

    /**
     * Gets the value of the wallTimeScalingFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getWallTimeScalingFactor() {
        return wallTimeScalingFactor;
    }

    /**
     * Sets the value of the wallTimeScalingFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setWallTimeScalingFactor(Float value) {
        this.wallTimeScalingFactor = value;
    }

    /**
     * Gets the value of the mainMemorySize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMainMemorySize() {
        return mainMemorySize;
    }

    /**
     * Sets the value of the mainMemorySize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMainMemorySize(BigInteger value) {
        this.mainMemorySize = value;
    }

    /**
     * Gets the value of the virtualMemorySize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVirtualMemorySize() {
        return virtualMemorySize;
    }

    /**
     * Sets the value of the virtualMemorySize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVirtualMemorySize(BigInteger value) {
        this.virtualMemorySize = value;
    }

    /**
     * Gets the value of the osFamily property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSFamily() {
        return osFamily;
    }

    /**
     * Sets the value of the osFamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSFamily(String value) {
        this.osFamily = value;
    }

    /**
     * Gets the value of the osName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSName() {
        return osName;
    }

    /**
     * Sets the value of the osName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSName(String value) {
        this.osName = value;
    }

    /**
     * Gets the value of the osVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSVersion() {
        return osVersion;
    }

    /**
     * Sets the value of the osVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSVersion(String value) {
        this.osVersion = value;
    }

    /**
     * Gets the value of the connectivityIn property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isConnectivityIn() {
        return connectivityIn;
    }

    /**
     * Sets the value of the connectivityIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setConnectivityIn(Boolean value) {
        this.connectivityIn = value;
    }

    /**
     * Gets the value of the connectivityOut property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isConnectivityOut() {
        return connectivityOut;
    }

    /**
     * Sets the value of the connectivityOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setConnectivityOut(Boolean value) {
        this.connectivityOut = value;
    }

    /**
     * Gets the value of the networkInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkInfo() {
        return networkInfo;
    }

    /**
     * Sets the value of the networkInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkInfo(String value) {
        this.networkInfo = value;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionsT }
     *     
     */
    public ExtensionsT getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionsT }
     *     
     */
    public void setExtensions(ExtensionsT value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the benchmark property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the benchmark property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBenchmark().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BenchmarkT }
     * 
     * 
     */
    public List<BenchmarkT> getBenchmark() {
        if (benchmark == null) {
            benchmark = new ArrayList<BenchmarkT>();
        }
        return this.benchmark;
    }

    /**
     * Gets the value of the associations property.
     * 
     * @return
     *     possible object is
     *     {@link Associations }
     *     
     */
    public Associations getAssociations() {
        return associations;
    }

    /**
     * Sets the value of the associations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Associations }
     *     
     */
    public void setAssociations(Associations value) {
        this.associations = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ComputingShareLocalID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="ApplicationEnvironmentLocalID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="ComputingActivityID" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ID_t" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "computingShareLocalID",
        "applicationEnvironmentLocalID",
        "computingActivityID"
    })
    public static class Associations {

        @XmlElement(name = "ComputingShareLocalID", required = true)
        protected List<String> computingShareLocalID;
        @XmlElement(name = "ApplicationEnvironmentLocalID", required = true)
        protected List<String> applicationEnvironmentLocalID;
        @XmlElement(name = "ComputingActivityID", required = true)
        protected List<String> computingActivityID;

        /**
         * Gets the value of the computingShareLocalID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the computingShareLocalID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getComputingShareLocalID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getComputingShareLocalID() {
            if (computingShareLocalID == null) {
                computingShareLocalID = new ArrayList<String>();
            }
            return this.computingShareLocalID;
        }

        /**
         * Gets the value of the applicationEnvironmentLocalID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the applicationEnvironmentLocalID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getApplicationEnvironmentLocalID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getApplicationEnvironmentLocalID() {
            if (applicationEnvironmentLocalID == null) {
                applicationEnvironmentLocalID = new ArrayList<String>();
            }
            return this.applicationEnvironmentLocalID;
        }

        /**
         * Gets the value of the computingActivityID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the computingActivityID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getComputingActivityID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getComputingActivityID() {
            if (computingActivityID == null) {
                computingActivityID = new ArrayList<String>();
            }
            return this.computingActivityID;
        }

    }

}
