//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 05:26:33 PM CEST 
//


package com.terradue.ogf.schema.glue.impl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.terradue.ogf.schema.glue.impl.AdminDomainT.Services;
import com.terradue.ogf.schema.glue.impl.ComputingManagerT.ApplicationEnvironments;
import com.terradue.ogf.schema.glue.impl.ComputingServiceT.ComputingActivitites;
import com.terradue.ogf.schema.glue.impl.ComputingServiceT.ComputingShares;
import com.terradue.ogf.schema.glue.impl.ServiceT.Activities;
import com.terradue.ogf.schema.glue.impl.StorageServiceT.StorageShares;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.terradue.ogf.schema.glue.impl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Domains_QNAME = new QName("http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01", "Domains");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.terradue.ogf.schema.glue.impl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ActivityT }
     * 
     */
    public ActivityT createActivityT() {
        return new ActivityT();
    }

    /**
     * Create an instance of {@link ComputingEndpointT }
     * 
     */
    public ComputingEndpointT createComputingEndpointT() {
        return new ComputingEndpointT();
    }

    /**
     * Create an instance of {@link com.terradue.ogf.schema.glue.impl.ComputingShareT.Associations }
     * 
     */
    public com.terradue.ogf.schema.glue.impl.ComputingShareT.Associations createComputingShareTAssociations() {
        return new com.terradue.ogf.schema.glue.impl.ComputingShareT.Associations();
    }

    /**
     * Create an instance of {@link AdminDomainT }
     * 
     */
    public AdminDomainT createAdminDomainT() {
        return new AdminDomainT();
    }

    /**
     * Create an instance of {@link ComputingActivityT }
     * 
     */
    public ComputingActivityT createComputingActivityT() {
        return new ComputingActivityT();
    }

    /**
     * Create an instance of {@link StorageResourceT }
     * 
     */
    public StorageResourceT createStorageResourceT() {
        return new StorageResourceT();
    }

    /**
     * Create an instance of {@link ServicePropertiesT }
     * 
     */
    public ServicePropertiesT createServicePropertiesT() {
        return new ServicePropertiesT();
    }

    /**
     * Create an instance of {@link StorageServiceCapacityT }
     * 
     */
    public StorageServiceCapacityT createStorageServiceCapacityT() {
        return new StorageServiceCapacityT();
    }

    /**
     * Create an instance of {@link com.terradue.ogf.schema.glue.impl.ComputingEndpointT.Associations }
     * 
     */
    public com.terradue.ogf.schema.glue.impl.ComputingEndpointT.Associations createComputingEndpointTAssociations() {
        return new com.terradue.ogf.schema.glue.impl.ComputingEndpointT.Associations();
    }

    /**
     * Create an instance of {@link ComputingShareT }
     * 
     */
    public ComputingShareT createComputingShareT() {
        return new ComputingShareT();
    }

    /**
     * Create an instance of {@link MappingPolicyT }
     * 
     */
    public MappingPolicyT createMappingPolicyT() {
        return new MappingPolicyT();
    }

    /**
     * Create an instance of {@link com.terradue.ogf.schema.glue.impl.ServiceT.Associations }
     * 
     */
    public com.terradue.ogf.schema.glue.impl.ServiceT.Associations createServiceTAssociations() {
        return new com.terradue.ogf.schema.glue.impl.ServiceT.Associations();
    }

    /**
     * Create an instance of {@link UserDomainT }
     * 
     */
    public UserDomainT createUserDomainT() {
        return new UserDomainT();
    }

    /**
     * Create an instance of {@link DomainsT }
     * 
     */
    public DomainsT createDomainsT() {
        return new DomainsT();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link com.terradue.ogf.schema.glue.impl.ApplicationEnvironmentT.Associations }
     * 
     */
    public com.terradue.ogf.schema.glue.impl.ApplicationEnvironmentT.Associations createApplicationEnvironmentTAssociations() {
        return new com.terradue.ogf.schema.glue.impl.ApplicationEnvironmentT.Associations();
    }

    /**
     * Create an instance of {@link EndpointPropertiesT }
     * 
     */
    public EndpointPropertiesT createEndpointPropertiesT() {
        return new EndpointPropertiesT();
    }

    /**
     * Create an instance of {@link com.terradue.ogf.schema.glue.impl.ToComputingServiceT.Associations }
     * 
     */
    public com.terradue.ogf.schema.glue.impl.ToComputingServiceT.Associations createToComputingServiceTAssociations() {
        return new com.terradue.ogf.schema.glue.impl.ToComputingServiceT.Associations();
    }

    /**
     * Create an instance of {@link com.terradue.ogf.schema.glue.impl.UserDomainT.Associations }
     * 
     */
    public com.terradue.ogf.schema.glue.impl.UserDomainT.Associations createUserDomainTAssociations() {
        return new com.terradue.ogf.schema.glue.impl.UserDomainT.Associations();
    }

    /**
     * Create an instance of {@link ExecutionEnvironmentT }
     * 
     */
    public ExecutionEnvironmentT createExecutionEnvironmentT() {
        return new ExecutionEnvironmentT();
    }

    /**
     * Create an instance of {@link com.terradue.ogf.schema.glue.impl.StorageResourceT.Associations }
     * 
     */
    public com.terradue.ogf.schema.glue.impl.StorageResourceT.Associations createStorageResourceTAssociations() {
        return new com.terradue.ogf.schema.glue.impl.StorageResourceT.Associations();
    }

    /**
     * Create an instance of {@link StorageShareT }
     * 
     */
    public StorageShareT createStorageShareT() {
        return new StorageShareT();
    }

    /**
     * Create an instance of {@link StorageManagerT }
     * 
     */
    public StorageManagerT createStorageManagerT() {
        return new StorageManagerT();
    }

    /**
     * Create an instance of {@link ApplicationEnvironments }
     * 
     */
    public ApplicationEnvironments createComputingManagerTApplicationEnvironments() {
        return new ApplicationEnvironments();
    }

    /**
     * Create an instance of {@link ComputingShares }
     * 
     */
    public ComputingShares createComputingServiceTComputingShares() {
        return new ComputingShares();
    }

    /**
     * Create an instance of {@link ExtensionT }
     * 
     */
    public ExtensionT createExtensionT() {
        return new ExtensionT();
    }

    /**
     * Create an instance of {@link com.terradue.ogf.schema.glue.impl.StorageShareT.Associations }
     * 
     */
    public com.terradue.ogf.schema.glue.impl.StorageShareT.Associations createStorageShareTAssociations() {
        return new com.terradue.ogf.schema.glue.impl.StorageShareT.Associations();
    }

    /**
     * Create an instance of {@link com.terradue.ogf.schema.glue.impl.ComputingActivityT.Associations }
     * 
     */
    public com.terradue.ogf.schema.glue.impl.ComputingActivityT.Associations createComputingActivityTAssociations() {
        return new com.terradue.ogf.schema.glue.impl.ComputingActivityT.Associations();
    }

    /**
     * Create an instance of {@link ApplicationEnvironmentT }
     * 
     */
    public ApplicationEnvironmentT createApplicationEnvironmentT() {
        return new ApplicationEnvironmentT();
    }

    /**
     * Create an instance of {@link com.terradue.ogf.schema.glue.impl.ToStorageServiceT.Associations }
     * 
     */
    public com.terradue.ogf.schema.glue.impl.ToStorageServiceT.Associations createToStorageServiceTAssociations() {
        return new com.terradue.ogf.schema.glue.impl.ToStorageServiceT.Associations();
    }

    /**
     * Create an instance of {@link StorageAccessProtocolT }
     * 
     */
    public StorageAccessProtocolT createStorageAccessProtocolT() {
        return new StorageAccessProtocolT();
    }

    /**
     * Create an instance of {@link AccessPolicyT }
     * 
     */
    public AccessPolicyT createAccessPolicyT() {
        return new AccessPolicyT();
    }

    /**
     * Create an instance of {@link StorageShares }
     * 
     */
    public StorageShares createStorageServiceTStorageShares() {
        return new StorageShares();
    }

    /**
     * Create an instance of {@link com.terradue.ogf.schema.glue.impl.ActivityT.Associations }
     * 
     */
    public com.terradue.ogf.schema.glue.impl.ActivityT.Associations createActivityTAssociations() {
        return new com.terradue.ogf.schema.glue.impl.ActivityT.Associations();
    }

    /**
     * Create an instance of {@link StorageShareCapacityT }
     * 
     */
    public StorageShareCapacityT createStorageShareCapacityT() {
        return new StorageShareCapacityT();
    }

    /**
     * Create an instance of {@link com.terradue.ogf.schema.glue.impl.EndpointT.Associations }
     * 
     */
    public com.terradue.ogf.schema.glue.impl.EndpointT.Associations createEndpointTAssociations() {
        return new com.terradue.ogf.schema.glue.impl.EndpointT.Associations();
    }

    /**
     * Create an instance of {@link ComputingActivitites }
     * 
     */
    public ComputingActivitites createComputingServiceTComputingActivitites() {
        return new ComputingActivitites();
    }

    /**
     * Create an instance of {@link com.terradue.ogf.schema.glue.impl.ComputingServiceT.Associations }
     * 
     */
    public com.terradue.ogf.schema.glue.impl.ComputingServiceT.Associations createComputingServiceTAssociations() {
        return new com.terradue.ogf.schema.glue.impl.ComputingServiceT.Associations();
    }

    /**
     * Create an instance of {@link ToComputingServiceT }
     * 
     */
    public ToComputingServiceT createToComputingServiceT() {
        return new ToComputingServiceT();
    }

    /**
     * Create an instance of {@link ContactT }
     * 
     */
    public ContactT createContactT() {
        return new ContactT();
    }

    /**
     * Create an instance of {@link StorageEndpointT }
     * 
     */
    public StorageEndpointT createStorageEndpointT() {
        return new StorageEndpointT();
    }

    /**
     * Create an instance of {@link ComputingServiceT }
     * 
     */
    public ComputingServiceT createComputingServiceT() {
        return new ComputingServiceT();
    }

    /**
     * Create an instance of {@link ServiceT }
     * 
     */
    public ServiceT createServiceT() {
        return new ServiceT();
    }

    /**
     * Create an instance of {@link Services }
     * 
     */
    public Services createAdminDomainTServices() {
        return new Services();
    }

    /**
     * Create an instance of {@link ToStorageServiceT }
     * 
     */
    public ToStorageServiceT createToStorageServiceT() {
        return new ToStorageServiceT();
    }

    /**
     * Create an instance of {@link ComputingManagerT }
     * 
     */
    public ComputingManagerT createComputingManagerT() {
        return new ComputingManagerT();
    }

    /**
     * Create an instance of {@link com.terradue.ogf.schema.glue.impl.StorageEndpointT.Associations }
     * 
     */
    public com.terradue.ogf.schema.glue.impl.StorageEndpointT.Associations createStorageEndpointTAssociations() {
        return new com.terradue.ogf.schema.glue.impl.StorageEndpointT.Associations();
    }

    /**
     * Create an instance of {@link com.terradue.ogf.schema.glue.impl.AdminDomainT.Associations }
     * 
     */
    public com.terradue.ogf.schema.glue.impl.AdminDomainT.Associations createAdminDomainTAssociations() {
        return new com.terradue.ogf.schema.glue.impl.AdminDomainT.Associations();
    }

    /**
     * Create an instance of {@link com.terradue.ogf.schema.glue.impl.ExecutionEnvironmentT.Associations }
     * 
     */
    public com.terradue.ogf.schema.glue.impl.ExecutionEnvironmentT.Associations createExecutionEnvironmentTAssociations() {
        return new com.terradue.ogf.schema.glue.impl.ExecutionEnvironmentT.Associations();
    }

    /**
     * Create an instance of {@link StorageServiceT }
     * 
     */
    public StorageServiceT createStorageServiceT() {
        return new StorageServiceT();
    }

    /**
     * Create an instance of {@link ActivityPropertiesT }
     * 
     */
    public ActivityPropertiesT createActivityPropertiesT() {
        return new ActivityPropertiesT();
    }

    /**
     * Create an instance of {@link EndpointT }
     * 
     */
    public EndpointT createEndpointT() {
        return new EndpointT();
    }

    /**
     * Create an instance of {@link Activities }
     * 
     */
    public Activities createServiceTActivities() {
        return new Activities();
    }

    /**
     * Create an instance of {@link ApplicationHandleT }
     * 
     */
    public ApplicationHandleT createApplicationHandleT() {
        return new ApplicationHandleT();
    }

    /**
     * Create an instance of {@link ExtensionsT }
     * 
     */
    public ExtensionsT createExtensionsT() {
        return new ExtensionsT();
    }

    /**
     * Create an instance of {@link LocationT }
     * 
     */
    public LocationT createLocationT() {
        return new LocationT();
    }

    /**
     * Create an instance of {@link BenchmarkT }
     * 
     */
    public BenchmarkT createBenchmarkT() {
        return new BenchmarkT();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DomainsT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01", name = "Domains")
    public JAXBElement<DomainsT> createDomains(DomainsT value) {
        return new JAXBElement<DomainsT>(_Domains_QNAME, DomainsT.class, null, value);
    }

}
