//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 05:26:33 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01")
package com.terradue.ogf.schema.glue.impl;
