//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 05:26:33 PM CEST 
//


package com.terradue.ogf.schema.glue.impl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for RetentionPolicy_t.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RetentionPolicy_t">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="custodial"/>
 *     &lt;enumeration value="output"/>
 *     &lt;enumeration value="replica"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum RetentionPolicyT {

    @XmlEnumValue("custodial")
    CUSTODIAL("custodial"),
    @XmlEnumValue("output")
    OUTPUT("output"),
    @XmlEnumValue("replica")
    REPLICA("replica");
    private final String value;

    RetentionPolicyT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RetentionPolicyT fromValue(String v) {
        for (RetentionPolicyT c: RetentionPolicyT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
