//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 05:26:33 PM CEST 
//


package com.terradue.ogf.schema.glue.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.terradue.ogf.schema.glue.impl.StorageServiceT.StorageShares;


/**
 * <p>Java class for StorageService_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StorageService_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ServiceProperties_t">
 *       &lt;sequence>
 *         &lt;element name="StorageServiceCapacity" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}StorageServiceCapacity_t" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StorageAccessProtocol" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}StorageAccessProtocol_t" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StorageEndpoint" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}StorageEndpoint_t" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StorageShares" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="StorageShare" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}StorageShare_t" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="StorageManager" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}StorageManager_t" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ToComputingService" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ToComputingService_t" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StorageService_t", propOrder = {
    "storageServiceCapacity",
    "storageAccessProtocol",
    "storageEndpoint",
    "storageShares",
    "storageManager",
    "toComputingService"
})
public class StorageServiceT
    extends ServicePropertiesT
{

    @XmlElement(name = "StorageServiceCapacity", required = true)
    protected List<StorageServiceCapacityT> storageServiceCapacity;
    @XmlElement(name = "StorageAccessProtocol", required = true)
    protected List<StorageAccessProtocolT> storageAccessProtocol;
    @XmlElement(name = "StorageEndpoint", required = true)
    protected List<StorageEndpointT> storageEndpoint;
    @XmlElement(name = "StorageShares")
    protected StorageShares storageShares;
    @XmlElement(name = "StorageManager", required = true)
    protected List<StorageManagerT> storageManager;
    @XmlElement(name = "ToComputingService", required = true)
    protected List<ToComputingServiceT> toComputingService;

    /**
     * Gets the value of the storageServiceCapacity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the storageServiceCapacity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStorageServiceCapacity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StorageServiceCapacityT }
     * 
     * 
     */
    public List<StorageServiceCapacityT> getStorageServiceCapacity() {
        if (storageServiceCapacity == null) {
            storageServiceCapacity = new ArrayList<StorageServiceCapacityT>();
        }
        return this.storageServiceCapacity;
    }

    /**
     * Gets the value of the storageAccessProtocol property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the storageAccessProtocol property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStorageAccessProtocol().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StorageAccessProtocolT }
     * 
     * 
     */
    public List<StorageAccessProtocolT> getStorageAccessProtocol() {
        if (storageAccessProtocol == null) {
            storageAccessProtocol = new ArrayList<StorageAccessProtocolT>();
        }
        return this.storageAccessProtocol;
    }

    /**
     * Gets the value of the storageEndpoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the storageEndpoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStorageEndpoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StorageEndpointT }
     * 
     * 
     */
    public List<StorageEndpointT> getStorageEndpoint() {
        if (storageEndpoint == null) {
            storageEndpoint = new ArrayList<StorageEndpointT>();
        }
        return this.storageEndpoint;
    }

    /**
     * Gets the value of the storageShares property.
     * 
     * @return
     *     possible object is
     *     {@link StorageShares }
     *     
     */
    public StorageShares getStorageShares() {
        return storageShares;
    }

    /**
     * Sets the value of the storageShares property.
     * 
     * @param value
     *     allowed object is
     *     {@link StorageShares }
     *     
     */
    public void setStorageShares(StorageShares value) {
        this.storageShares = value;
    }

    /**
     * Gets the value of the storageManager property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the storageManager property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStorageManager().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StorageManagerT }
     * 
     * 
     */
    public List<StorageManagerT> getStorageManager() {
        if (storageManager == null) {
            storageManager = new ArrayList<StorageManagerT>();
        }
        return this.storageManager;
    }

    /**
     * Gets the value of the toComputingService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the toComputingService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getToComputingService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ToComputingServiceT }
     * 
     * 
     */
    public List<ToComputingServiceT> getToComputingService() {
        if (toComputingService == null) {
            toComputingService = new ArrayList<ToComputingServiceT>();
        }
        return this.toComputingService;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="StorageShare" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}StorageShare_t" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "storageShare"
    })
    public static class StorageShares {

        @XmlElement(name = "StorageShare", required = true)
        protected List<StorageShareT> storageShare;

        /**
         * Gets the value of the storageShare property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the storageShare property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStorageShare().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StorageShareT }
         * 
         * 
         */
        public List<StorageShareT> getStorageShare() {
            if (storageShare == null) {
                storageShare = new ArrayList<StorageShareT>();
            }
            return this.storageShare;
        }

    }

}
