//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 05:26:33 PM CEST 
//


package com.terradue.ogf.schema.glue.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.terradue.ogf.schema.glue.impl.StorageShareT.Associations;


/**
 * <p>Java class for StorageShare_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StorageShare_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}Share_t">
 *       &lt;sequence>
 *         &lt;element name="ServingState" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ServingState_t"/>
 *         &lt;element name="Path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SharingID" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}LocalID_t"/>
 *         &lt;element name="AccessLatency" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}AccessLatency_t"/>
 *         &lt;element name="RetentionPolicy" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}RetentionPolicy_t" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ExpirationMode" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ExpirationMode_t" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="DefaultLifeTime" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="MaximumLifeTime" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="Tag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OtherInfo" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Extensions" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}Extensions_t" minOccurs="0"/>
 *         &lt;element name="MappingPolicy" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}MappingPolicy_t" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StorageShareCapacity" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}StorageShareCapacity_t" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Associations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="StorageEndpointID" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ID_t" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="StorageResourceID" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ID_t" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StorageShare_t", propOrder = {
    "servingState",
    "path",
    "sharingID",
    "accessLatency",
    "retentionPolicy",
    "expirationMode",
    "defaultLifeTime",
    "maximumLifeTime",
    "tag",
    "otherInfo",
    "extensions",
    "mappingPolicy",
    "storageShareCapacity",
    "associations"
})
public class StorageShareT
    extends ShareT
{

    @XmlElement(name = "ServingState", required = true)
    protected ServingStateT servingState;
    @XmlElement(name = "Path", required = true)
    protected String path;
    @XmlElement(name = "SharingID", required = true)
    protected String sharingID;
    @XmlElement(name = "AccessLatency", required = true)
    protected AccessLatencyT accessLatency;
    @XmlElement(name = "RetentionPolicy", required = true)
    protected List<RetentionPolicyT> retentionPolicy;
    @XmlElement(name = "ExpirationMode", required = true)
    protected List<ExpirationModeT> expirationMode;
    @XmlElement(name = "DefaultLifeTime")
    protected Long defaultLifeTime;
    @XmlElement(name = "MaximumLifeTime")
    protected Long maximumLifeTime;
    @XmlElement(name = "Tag")
    protected String tag;
    @XmlElement(name = "OtherInfo", required = true)
    protected List<String> otherInfo;
    @XmlElement(name = "Extensions")
    protected ExtensionsT extensions;
    @XmlElement(name = "MappingPolicy", required = true)
    protected List<MappingPolicyT> mappingPolicy;
    @XmlElement(name = "StorageShareCapacity", required = true)
    protected List<StorageShareCapacityT> storageShareCapacity;
    @XmlElement(name = "Associations")
    protected Associations associations;

    /**
     * Gets the value of the servingState property.
     * 
     * @return
     *     possible object is
     *     {@link ServingStateT }
     *     
     */
    public ServingStateT getServingState() {
        return servingState;
    }

    /**
     * Sets the value of the servingState property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServingStateT }
     *     
     */
    public void setServingState(ServingStateT value) {
        this.servingState = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the sharingID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSharingID() {
        return sharingID;
    }

    /**
     * Sets the value of the sharingID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSharingID(String value) {
        this.sharingID = value;
    }

    /**
     * Gets the value of the accessLatency property.
     * 
     * @return
     *     possible object is
     *     {@link AccessLatencyT }
     *     
     */
    public AccessLatencyT getAccessLatency() {
        return accessLatency;
    }

    /**
     * Sets the value of the accessLatency property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessLatencyT }
     *     
     */
    public void setAccessLatency(AccessLatencyT value) {
        this.accessLatency = value;
    }

    /**
     * Gets the value of the retentionPolicy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the retentionPolicy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRetentionPolicy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RetentionPolicyT }
     * 
     * 
     */
    public List<RetentionPolicyT> getRetentionPolicy() {
        if (retentionPolicy == null) {
            retentionPolicy = new ArrayList<RetentionPolicyT>();
        }
        return this.retentionPolicy;
    }

    /**
     * Gets the value of the expirationMode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the expirationMode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExpirationMode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExpirationModeT }
     * 
     * 
     */
    public List<ExpirationModeT> getExpirationMode() {
        if (expirationMode == null) {
            expirationMode = new ArrayList<ExpirationModeT>();
        }
        return this.expirationMode;
    }

    /**
     * Gets the value of the defaultLifeTime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDefaultLifeTime() {
        return defaultLifeTime;
    }

    /**
     * Sets the value of the defaultLifeTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDefaultLifeTime(Long value) {
        this.defaultLifeTime = value;
    }

    /**
     * Gets the value of the maximumLifeTime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaximumLifeTime() {
        return maximumLifeTime;
    }

    /**
     * Sets the value of the maximumLifeTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaximumLifeTime(Long value) {
        this.maximumLifeTime = value;
    }

    /**
     * Gets the value of the tag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTag() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTag(String value) {
        this.tag = value;
    }

    /**
     * Gets the value of the otherInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOtherInfo() {
        if (otherInfo == null) {
            otherInfo = new ArrayList<String>();
        }
        return this.otherInfo;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionsT }
     *     
     */
    public ExtensionsT getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionsT }
     *     
     */
    public void setExtensions(ExtensionsT value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the mappingPolicy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mappingPolicy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMappingPolicy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MappingPolicyT }
     * 
     * 
     */
    public List<MappingPolicyT> getMappingPolicy() {
        if (mappingPolicy == null) {
            mappingPolicy = new ArrayList<MappingPolicyT>();
        }
        return this.mappingPolicy;
    }

    /**
     * Gets the value of the storageShareCapacity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the storageShareCapacity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStorageShareCapacity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StorageShareCapacityT }
     * 
     * 
     */
    public List<StorageShareCapacityT> getStorageShareCapacity() {
        if (storageShareCapacity == null) {
            storageShareCapacity = new ArrayList<StorageShareCapacityT>();
        }
        return this.storageShareCapacity;
    }

    /**
     * Gets the value of the associations property.
     * 
     * @return
     *     possible object is
     *     {@link Associations }
     *     
     */
    public Associations getAssociations() {
        return associations;
    }

    /**
     * Sets the value of the associations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Associations }
     *     
     */
    public void setAssociations(Associations value) {
        this.associations = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="StorageEndpointID" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ID_t" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="StorageResourceID" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ID_t" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "storageEndpointID",
        "storageResourceID"
    })
    public static class Associations {

        @XmlElement(name = "StorageEndpointID", required = true)
        protected List<String> storageEndpointID;
        @XmlElement(name = "StorageResourceID", required = true)
        protected List<String> storageResourceID;

        /**
         * Gets the value of the storageEndpointID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the storageEndpointID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStorageEndpointID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getStorageEndpointID() {
            if (storageEndpointID == null) {
                storageEndpointID = new ArrayList<String>();
            }
            return this.storageEndpointID;
        }

        /**
         * Gets the value of the storageResourceID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the storageResourceID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStorageResourceID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getStorageResourceID() {
            if (storageResourceID == null) {
                storageResourceID = new ArrayList<String>();
            }
            return this.storageResourceID;
        }

    }

}
