//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 05:26:33 PM CEST 
//


package com.terradue.ogf.schema.glue.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.terradue.ogf.schema.glue.impl.ToComputingServiceT.Associations;


/**
 * <p>Java class for ToComputingService_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ToComputingService_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}Entity">
 *       &lt;sequence>
 *         &lt;element name="LocalID" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}LocalID_t"/>
 *         &lt;element name="NetworkInfo" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}NetworkInfo_t" minOccurs="0"/>
 *         &lt;element name="Bandwidth" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="OtherInfo" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Extensions" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}Extensions_t" minOccurs="0"/>
 *         &lt;element name="Associations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="StorageAccessProtocolLocalID" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ID_t" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="ComputingServiceID" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="StorageServiceID" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ToComputingService_t", propOrder = {
    "localID",
    "networkInfo",
    "bandwidth",
    "otherInfo",
    "extensions",
    "associations"
})
public class ToComputingServiceT
    extends Entity
{

    @XmlElement(name = "LocalID", required = true)
    protected String localID;
    @XmlElement(name = "NetworkInfo")
    protected String networkInfo;
    @XmlElement(name = "Bandwidth")
    protected Long bandwidth;
    @XmlElement(name = "OtherInfo", required = true)
    protected List<String> otherInfo;
    @XmlElement(name = "Extensions")
    protected ExtensionsT extensions;
    @XmlElement(name = "Associations")
    protected Associations associations;

    /**
     * Gets the value of the localID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalID() {
        return localID;
    }

    /**
     * Sets the value of the localID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalID(String value) {
        this.localID = value;
    }

    /**
     * Gets the value of the networkInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkInfo() {
        return networkInfo;
    }

    /**
     * Sets the value of the networkInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkInfo(String value) {
        this.networkInfo = value;
    }

    /**
     * Gets the value of the bandwidth property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBandwidth() {
        return bandwidth;
    }

    /**
     * Sets the value of the bandwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBandwidth(Long value) {
        this.bandwidth = value;
    }

    /**
     * Gets the value of the otherInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOtherInfo() {
        if (otherInfo == null) {
            otherInfo = new ArrayList<String>();
        }
        return this.otherInfo;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionsT }
     *     
     */
    public ExtensionsT getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionsT }
     *     
     */
    public void setExtensions(ExtensionsT value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the associations property.
     * 
     * @return
     *     possible object is
     *     {@link Associations }
     *     
     */
    public Associations getAssociations() {
        return associations;
    }

    /**
     * Sets the value of the associations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Associations }
     *     
     */
    public void setAssociations(Associations value) {
        this.associations = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="StorageAccessProtocolLocalID" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}ID_t" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="ComputingServiceID" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="StorageServiceID" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "storageAccessProtocolLocalID",
        "computingServiceID",
        "storageServiceID"
    })
    public static class Associations {

        @XmlElement(name = "StorageAccessProtocolLocalID", required = true)
        protected List<String> storageAccessProtocolLocalID;
        @XmlElement(name = "ComputingServiceID", required = true)
        protected String computingServiceID;
        @XmlElement(name = "StorageServiceID", required = true)
        protected String storageServiceID;

        /**
         * Gets the value of the storageAccessProtocolLocalID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the storageAccessProtocolLocalID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStorageAccessProtocolLocalID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getStorageAccessProtocolLocalID() {
            if (storageAccessProtocolLocalID == null) {
                storageAccessProtocolLocalID = new ArrayList<String>();
            }
            return this.storageAccessProtocolLocalID;
        }

        /**
         * Gets the value of the computingServiceID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComputingServiceID() {
            return computingServiceID;
        }

        /**
         * Sets the value of the computingServiceID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComputingServiceID(String value) {
            this.computingServiceID = value;
        }

        /**
         * Gets the value of the storageServiceID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStorageServiceID() {
            return storageServiceID;
        }

        /**
         * Sets the value of the storageServiceID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStorageServiceID(String value) {
            this.storageServiceID = value;
        }

    }

}
