//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 05:26:33 PM CEST 
//


package com.terradue.ogf.schema.glue.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.terradue.ogf.schema.glue.impl.ToStorageServiceT.Associations;


/**
 * <p>Java class for ToStorageService_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ToStorageService_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}Entity">
 *       &lt;sequence>
 *         &lt;element name="LocalID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LocalPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RemotePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Extensions" type="{http://schemas.ogf.org/glue/2008/05/spec_2.0_d42_r01}Extensions_t" minOccurs="0"/>
 *         &lt;element name="Associations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ComputingServiceID" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="StorageServiceID" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ToStorageService_t", propOrder = {
    "localID",
    "localPath",
    "remotePath",
    "extensions",
    "associations"
})
public class ToStorageServiceT
    extends Entity
{

    @XmlElement(name = "LocalID", required = true)
    protected String localID;
    @XmlElement(name = "LocalPath", required = true)
    protected String localPath;
    @XmlElement(name = "RemotePath", required = true)
    protected String remotePath;
    @XmlElement(name = "Extensions")
    protected ExtensionsT extensions;
    @XmlElement(name = "Associations")
    protected Associations associations;

    /**
     * Gets the value of the localID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalID() {
        return localID;
    }

    /**
     * Sets the value of the localID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalID(String value) {
        this.localID = value;
    }

    /**
     * Gets the value of the localPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalPath() {
        return localPath;
    }

    /**
     * Sets the value of the localPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalPath(String value) {
        this.localPath = value;
    }

    /**
     * Gets the value of the remotePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemotePath() {
        return remotePath;
    }

    /**
     * Sets the value of the remotePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemotePath(String value) {
        this.remotePath = value;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionsT }
     *     
     */
    public ExtensionsT getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionsT }
     *     
     */
    public void setExtensions(ExtensionsT value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the associations property.
     * 
     * @return
     *     possible object is
     *     {@link Associations }
     *     
     */
    public Associations getAssociations() {
        return associations;
    }

    /**
     * Sets the value of the associations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Associations }
     *     
     */
    public void setAssociations(Associations value) {
        this.associations = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ComputingServiceID" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="StorageServiceID" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "computingServiceID",
        "storageServiceID"
    })
    public static class Associations {

        @XmlElement(name = "ComputingServiceID", required = true)
        protected String computingServiceID;
        @XmlElement(name = "StorageServiceID", required = true)
        protected String storageServiceID;

        /**
         * Gets the value of the computingServiceID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComputingServiceID() {
            return computingServiceID;
        }

        /**
         * Sets the value of the computingServiceID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComputingServiceID(String value) {
            this.computingServiceID = value;
        }

        /**
         * Gets the value of the storageServiceID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStorageServiceID() {
            return storageServiceID;
        }

        /**
         * Sets the value of the storageServiceID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStorageServiceID(String value) {
            this.storageServiceID = value;
        }

    }

}
